(defpackage #:fx.prolog
  (:use #:cl)
  (:nicknames #:cl-cc/prolog)
  (:export
   #:fact
   #:fact-predicate
   #:fact-args
   #:make-fact
   #:rule
   #:rule-head
   #:rule-body
   #:make-rule
   #:rulebase
   #:rulebase-p
   #:rulebase-facts
   #:rulebase-rules
   #:make-rulebase
   #:make-empty-rule-knowledge-base
   #:clear-global-rulebase!
   #:register-rule!
   #:*prolog-rules*
   #:register-prolog-rule
   #:prolog-compound-form-parts
   #:*max-prolog-depth*
   #:logic-var-p
   #:variable-symbol-p
   #:unify
   #:unify-failed-p
   #:when-unify-succeeds
   #:when-unify-fails
   #:occurs-check
   #:logic-substitute
   #:substitute-term
   #:define-rulebase
   #:extend-rulebase
   #:with-prolog-query
   #:prolog-match
   #:query-prolog
   #:query-prolog-cps
   #:query-prolog-first
   #:prolog-succeeds-p
   #:prolog-succeeds-p-cps
   #:merge-rulebase-facts
   #:merge-rulebase-facts-cps
   #:query-all
   #:!
   #:!=
   #:/=
   #:dcg-token-match
   #:dcg-token-match-value
   #:def-rule
   #:*peephole-copy-prop-rules*
   #:*peephole-arithmetic-rules*
   #:*peephole-control-flow-rules*
   #:*peephole-rules*
   #:def-dcg-rule
   #:phrase
   #:phrase-all
   #:assert-fact!
   #:assert-rule!
   #:predicate-true-p
   #:prove
   #:prove-all))
