(defpackage #:fx.prolog.tests
  (:use #:cl #:fx.prolog)
  (:export #:run-tests))

(in-package #:fx.prolog.tests)

(declaim (special *test-rulebase*))

(defmethod predicate-true-p ((predicate (eql 'test-built-in)) args bindings)
  (declare (ignore bindings))
  (equal args '(:ok)))

(defun %check (condition message &rest args)
  (unless condition
    (error (apply #'format nil message args))))

(defun %equal-check (expected actual message)
  (%check (equal expected actual) "~A~%expected: ~S~%actual:   ~S" message expected actual))

(defun run-tests ()
  (clear-global-rulebase!)
  (let ((env (unify '?x '(a b c))))
    (%equal-check '((?x . (a b c))) env "unify binds a list")
    (%equal-check '((a b c) ?y) (list (logic-substitute '?x env) (logic-substitute '?y env))
                  "logic-substitute follows bindings"))
  (multiple-value-bind (env ok)
      (unify 1 2)
    (%check (unify-failed-p env) "failed unification returns the cl-cc sentinel as first value")
    (%check (not ok) "failed unification keeps the two-value success flag false"))
  (multiple-value-bind (env ok)
      (unify 1 1)
    (%check (null env) "ground unification success returns NIL as the environment")
    (%check ok "ground unification success keeps the two-value success flag true")
    (%check (not (unify-failed-p env)) "NIL ground-success environment is not a failed unification"))
  (let ((seen nil))
    (when-unify-succeeds (env '(tag ?x) '(tag value))
      (setf seen (logic-substitute '?x env)))
    (%equal-check 'value seen "when-unify-succeeds exposes the successful environment"))
  (let ((seen nil))
    (when-unify-fails ('(tag a) '(tag b))
      (setf seen t))
    (%check seen "when-unify-fails runs only for failed unification"))
  (%check (occurs-check '?x '(wrap ?x) '()) "occurs-check compatibility alias is available")
  (%check (variable-symbol-p '?x) "variable-symbol-p should alias logic-var-p")
  (%check (not (variable-symbol-p :?x)) "keywords are not Prolog variables")
  (%equal-check '(:outer (:inner . :buy) :buy)
                (substitute-term '(:outer (:inner . ?side) ?side)
                                 '((?side . :buy)))
                "substitute-term preserves dotted structure")
  (let ((rb (make-rulebase
              :facts (list (make-fact :predicate 'parent :args '(tom bob))
                           (make-fact :predicate 'parent :args '(bob alice)))
             :rules (list (make-rule :head '(ancestor ?x ?y)
                                     :body '((parent ?x ?y)))
                          (make-rule :head '(ancestor ?x ?y)
                                     :body '((parent ?x ?z) (ancestor ?z ?y)))))))
    (%equal-check '((?x . tom)) (query-prolog-first rb '(ancestor ?x bob))
                  "query-prolog projects variables in order")
    (%equal-check '(((?x . tom))) (prove-all rb '(ancestor ?x bob))
                  "prove-all returns projected variable bindings")
    (%check (prolog-succeeds-p rb '(ancestor tom alice))
            "recursive rule should succeed")
    (%check (prolog-succeeds-p rb '(/= tom alice))
            "/= should succeed when terms cannot unify")
    (%check (not (prolog-succeeds-p rb '(/= ?x ?y)))
            "/= should fail when unbound variables can unify")
    (%check (prolog-succeeds-p rb '(not (parent alice tom)))
            "not should succeed when nested goal fails")
    (%check (not (prolog-succeeds-p rb '(not (parent tom bob))))
            "not should fail when nested goal succeeds")
    (%equal-check '(nil) (query-prolog rb '(parent tom bob))
                  "ground success returns one empty binding list")
    (query-prolog-cps rb '(ancestor ?x bob)
                     (lambda (solutions)
                       (%equal-check '(((?x . tom))) solutions
                                     "query-prolog-cps returns query-prolog result")))
    (prolog-succeeds-p-cps rb '(ancestor tom bob)
                           (lambda (succeeds-p)
                             (%check succeeds-p "prolog-succeeds-p-cps returns success flag")))
    (merge-rulebase-facts-cps rb (list (make-fact :predicate 'parent :args '(alice eve)))
                              (lambda (merged)
                                (%check (prolog-succeeds-p merged '(parent alice eve))
                                        "merge-rulebase-facts-cps returns merged rulebase"))))
  (let ((rb (make-rulebase
             :facts (list '(raw-list-fact ok) :atom-fact)
             :rules '())))
    (%equal-check '(((?x . ok))) (query-prolog rb '(raw-list-fact ?x))
                  "raw list facts are queryable")
    (%equal-check '(nil) (query-prolog rb :atom-fact)
                  "atom facts are queryable"))
  (define-rulebase *test-rulebase*
    (:facts (parent tom bob) (parent bob alice))
    (:rules ((ancestor ?x ?y) (parent ?x ?y))
            ((ancestor ?x ?y) (parent ?x ?z) (ancestor ?z ?y))))
  (%check (prolog-succeeds-p *test-rulebase* '(ancestor tom alice))
          "define-rulebase should produce a queryable rulebase")
  (let ((extended (extend-rulebase *test-rulebase*
                    (:facts (parent alice eve))
                    (:rules ((grandparent ?x ?z) (parent ?x ?y) (parent ?y ?z))))))
    (%check (prolog-succeeds-p extended '(grandparent tom alice))
            "extend-rulebase prepends rules while retaining base clauses")
    (%check (not (prolog-succeeds-p *test-rulebase* '(parent alice eve)))
            "extend-rulebase does not mutate the base rulebase"))
  (%equal-check :matched
                (prolog-match *test-rulebase*
                  ('(ancestor tom alice) :matched)
                  ('(missing) :missing))
                "prolog-match evaluates the first successful clause")
  (with-prolog-query (?who) (*test-rulebase* '(ancestor tom ?who) :max-depth 1)
    (%equal-check 'bob ?who "with-prolog-query binds first-solution variables"))
  (%check (not (query-prolog *test-rulebase* '(ancestor tom alice) :max-depth 0))
          "max-depth 0 prevents recursive rule expansion")
  (let ((rb (make-rulebase
             :facts (list (make-fact :predicate 'color :args '(red))
                           (make-fact :predicate 'color :args '(green)))
             :rules (list (make-rule :head '(first-color ?c)
                                     :body '((color ?c) !))))))
    (%equal-check '(((?c . red))) (query-prolog rb '(first-color ?c))
                  "cut should keep only the first color"))
  (let ((rb (make-rulebase
             :facts (list (make-fact :predicate 'test-built-in :args '(:ok)))
             :rules '())))
    (%equal-check '(nil nil) (query-prolog rb '(test-built-in :ok))
                  "custom predicates and matching facts both contribute solutions"))
  (let ((rb (make-rulebase
             :facts (list (make-fact :predicate 'recursive :args '((?x (wrap ?x)))))
             :rules '())))
    (%check (not (query-prolog rb '(recursive ?x ?x)))
            "occurs-check prevents infinite bindings"))
  (let ((kb (make-empty-rule-knowledge-base)))
    (assert-fact! kb (make-fact :predicate 'feature :args '(empty-kb-alias)))
    (%check (prolog-succeeds-p kb '(feature empty-kb-alias))
            "make-empty-rule-knowledge-base should create a mutable rulebase"))
  (clear-global-rulebase!)
  (def-rule (global-parent tom bob))
  (%equal-check '((global-parent tom bob)) (query-all '(global-parent ?x bob))
                "query-all returns substituted global-rulebase goals")
  (clrhash *prolog-rules*)
  (%check (not (query-all '(global-parent ?x bob)))
          "query-all reflects direct cl-cc-style clearing of *prolog-rules*")
  (let ((rule (register-prolog-rule '(global-parent bob alice) '())))
    (%check (eq rule (first (gethash 'global-parent *prolog-rules*)))
            "register-prolog-rule indexes rules by predicate"))
  (%equal-check '((global-parent bob alice)) (query-all '(global-parent bob ?x))
                "query-all reads rules registered in *prolog-rules*")
  (let* ((rule (first *peephole-copy-prop-rules*))
         (env (unify (first rule) '(:const :r1 42)))
         (env (unless (unify-failed-p env)
                (unify (second rule) '(:move :r2 :r1) env))))
    (%check (not (unify-failed-p env))
            "peephole data works with cl-cc single-value unify")
    (%equal-check '((:const :r2 42))
                  (logic-substitute (third rule) env)
                  "peephole copy-prop rule substitutes matched operands"))
  (def-dcg-rule accept-one
    (terminal :word))
  (%equal-check '(:rest) (phrase 'accept-one '(:word :rest))
                "phrase should return remaining input")
  (%equal-check '((:rest)) (phrase-all 'accept-one '(:word :rest))
                "phrase-all returns all possible remaining streams")
  (def-dcg-rule accept-token-pair
    (terminal :T-INT))
  (%equal-check '((:T-EOF . nil)) (phrase 'accept-token-pair '((:T-INT . 1) (:T-EOF . nil)))
                "terminal matches token-pair kinds")
  (def-dcg-rule accept-guarded
    (brace t)
    (terminal :ok))
  (%equal-check nil (phrase 'accept-guarded '(:ok))
                "brace forms can guard DCG rules without consuming input")
  (%equal-check '(((?value . 42) (?rest)))
                (query-prolog fx.prolog::*global-rulebase*
                              '(dcg-token-match-value :T-INT ?value ((:T-INT . 42)) ?rest))
                "dcg-token-match-value binds token values")
  (format t "All cl-prolog tests passed.~%")
  t)
