(in-package #:cl-prolog.tests)

(deftest-queries term-builtins ((make-rulebase))
  ((cl-prolog::var ?x) :succeeds)
  ((and (= ?x value) (cl-prolog::var ?x)) :fails)
  ((cl-prolog::nonvar value) :succeeds)
  ((cl-prolog::nonvar ?x) :fails)
  ((cl-prolog::atom value) :succeeds)
  ((cl-prolog::atom 3) :fails)
  ((cl-prolog::number 3/2) :succeeds)
  ((cl-prolog::number value) :fails)
  ((cl-prolog::integer 3) :succeeds)
  ((cl-prolog::integer 3/2) :fails)
  ((cl-prolog::== value value) :succeeds)
  ((cl-prolog::== ?x ?x) :succeeds)
  ((cl-prolog::== ?x ?y) :fails)
  ((and (cl-prolog::|\\==| ?x ?y) (= ?x ?y)) :succeeds)
  ((cl-prolog::|\\==| (node ?x) (node ?x)) :fails)
  ((cl-prolog::@< ?x atom) :succeeds)
  ((cl-prolog::@< 2 atom) :succeeds)
  ((cl-prolog::@< atom (node)) :succeeds)
  ((cl-prolog::@< (a x) (b x)) :succeeds)
  ((cl-prolog::@=< (node left) (node left)) :succeeds)
  ((cl-prolog::@> (node right) atom) :succeeds)
  ((cl-prolog::@>= 2 2) :succeeds)
  ((cl-prolog::compare ?order 1 2) => (((?order . <))))
  ((cl-prolog::compare ?order value value) => (((?order . =))))
  ((cl-prolog::compare ?order (node) value) => (((?order . >))))
  ((cl-prolog::term-variables (pair ?x (nested ?y ?x)) ?variables)
   => (((?x . ?x) (?y . ?y) (?variables ?x ?y))))
  ((and (= ?x bound)
        (cl-prolog::term-variables (pair ?x ?y) ?variables))
   => (((?x . bound) (?y . ?y) (?variables ?y))))
  ((cl-prolog::compound (node left right)) :succeeds)
  ((cl-prolog::compound value) :fails)
  ((cl-prolog::ground (node left 3)) :succeeds)
  ((cl-prolog::ground (node ?x 3)) :fails)
  ((cl-prolog::functor (node left right) ?name ?arity)
   => (((?name . node) (?arity . 2))))
  ((cl-prolog::functor value ?name ?arity)
   => (((?name . value) (?arity . 0))))
  ((cl-prolog::functor ?term node 2) :succeeds)
  ((cl-prolog::functor ?term 7 0) => (((?term . 7))))
  ((cl-prolog::functor ?term 7 1) :fails)
  ((cl-prolog::arg 2 (node left right) ?value)
   => (((?value . right))))
  ((cl-prolog::arg 0 (node left right) ?value) :fails)
  ((cl-prolog::arg 3 (node left right) ?value) :fails)
  ((and (cl-prolog::copy-term (pair ?x ?x) ?copy)
        (= ?copy (pair copied copied)))
   :succeeds)
  ((and (cl-prolog::copy-term (pair ?x ?x) ?copy)
        (= ?copy (pair left right)))
   :fails)
  ((cl-prolog::|=..| (node left right) ?list)
   => (((?list node left right))))
  ((cl-prolog::|=..| value ?list)
   => (((?list value))))
  ((cl-prolog::|=..| ?term (node left right))
   => (((?term node left right))))
  ((cl-prolog::|=..| ?term (value))
   => (((?term . value))))
  ((cl-prolog::|=..| ?term (7 left)) :fails)
  ((cl-prolog::|=..| ?term ?list) :fails))
