;;;; List builtin tests: member/2, memberchk/2, select/3, and other
;;;; list-processing predicates, plus cyclic-list/cyclic-term handling.

(in-package #:cl-prolog.tests)

(deftest-queries list-builtins ((make-rulebase))
  ((member ?x (bob alice))       :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))      :ordered (nil))
  ((and (member ?x (a b . ?tail)) (= ?tail end))
                                   :ordered (((?x . a) (?tail . end))
                                       ((?x . b) (?tail . end))) :limit 2)
  ((and (member wanted ?unbound) (= ?unbound (wanted tail)))
                                   :ordered (((?unbound wanted tail))) :limit 1)
  ((cl-prolog::memberchk ?x (a b a)) :ordered (((?x . a))))
  ((cl-prolog::memberchk z (a b)) :fails)
  ((cl-prolog::memberchk wanted ?xs) :succeeds)
  ((cl-prolog::select ?x (a b a) ?rest)
                                   :ordered (((?x . a) (?rest b a))
                                       ((?x . b) (?rest a a))
                                       ((?x . a) (?rest a b))))
  ((cl-prolog::select b ?list (a c))
                                   :ordered (((?list . (b a c)))
                                       ((?list . (a b c)))
                                       ((?list . (a c b)))) :limit 3)
  ((and (cl-prolog::select b (a b . ?tail) ?rest)
        (= ?tail (c)))           :ordered (((?tail . (c)) (?rest a c))) :limit 1)
  ((cl-prolog::select z (a b . improper) ?rest) :fails)
  ((cl-prolog::nth0 1 (a b c) ?x) :ordered (((?x . b))))
  ((cl-prolog::nth0 ?n (a b c) ?x)
                                   :ordered (((?n . 0) (?x . a))
                                       ((?n . 1) (?x . b))
                                       ((?n . 2) (?x . c))))
  ((cl-prolog::nth1 ?n (a b c) b) :ordered (((?n . 2))))
  ((and (cl-prolog::nth0 2 (a . ?tail) c)
        (= ?tail (b c d)))       :ordered (((?tail b c d))))
  ((cl-prolog::nth0 3 (a b . improper) ?x) :fails)
  ((cl-prolog::nth0 -1 (a b) ?x) :signals)
  ((cl-prolog::nth0 not-an-integer (a b) ?x) :signals)
  ((cl-prolog::nth1 0 (a b) ?x) :signals)
  ((cl-prolog::last (a b c) ?x) :ordered (((?x . c))))
  ((cl-prolog::last (singleton) singleton) :succeeds)
  ((cl-prolog::last (a b . improper) ?x) :fails)
  ((and (cl-prolog::last (a b . ?tail) c) (= ?tail (c)))
                                   :ordered (((?tail . (c)))) :limit 1)
  ((cl-prolog::is_list ())       :succeeds)
  ((cl-prolog::is_list (a b c))  :succeeds)
  ((cl-prolog::is_list (a b . improper)) :fails)
  ((cl-prolog::is_list ?unbound) :fails)
  ((append (a b) (c) ?xs)        :ordered (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c))  :ordered (((?tail . (c)))))
  ((append ?left ?right (a b c)) :ordered (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append (a . ?tail) (c) (a b c))
                                   :ordered (((?tail . (b)))))
  ((and (append ?left ?right ?any) (= ?any (a b)))
                                   :ordered (((?left . ()) (?right . (a b)) (?any a b))
                                       ((?left . (a)) (?right . (b)) (?any a b))
                                       ((?left . (a b)) (?right . ()) (?any a b))) :limit 3)
  ((reverse (a b c) ?x)          :ordered (((?x . (c b a)))))
  ((reverse ?x (c b a))          :ordered (((?x . (a b c)))))
  ((reverse (a . ?tail) (c b a)) :ordered (((?tail . (b c)))))
  ((reverse atom other)          :fails)
  ((length (a b c) ?n)           :ordered (((?n . 3))))
  ((length ?xs 0)                :ordered (((?xs))))
  ((length ?xs 2)                :succeeds)
  ((and (length ?xs ?n) (= ?n 2)):succeeds)
  ((length (a b . ?tail) 4)      :succeeds)
  ((length ?xs -1)               :signals)
  ((length ?xs not-a-number)     :signals))

(in-package #:cl-prolog.tests)

(deftest cyclic-list-builtins-terminate ()
  (let* ((self-cycle (list 'a))
         (two-node-cycle (list 'a 'b))
         (shared-tail (list 'b 'c))
         (shared-list (cons 'a shared-tail))
         (rulebase (make-rulebase)))
    (setf (cdr self-cycle) self-cycle
          (cddr two-node-cycle) two-node-cycle)
    (labels ((solutions (predicate &rest arguments)
               (let ((environments '()))
                 (funcall (cl-prolog::%goal-solver predicate (length arguments))
                          (cons predicate arguments) rulebase nil nil
                          (lambda (environment)
                            (push environment environments)))
                 (nreverse environments)))
             (fails-without-looping (predicate &rest arguments)
               (is (null (apply #'solutions predicate arguments))))
             (check-cycle (cycle)
               (fails-without-looping 'cl-prolog::is_list cycle)
               (fails-without-looping 'cl-prolog::member 'missing cycle)
               (fails-without-looping 'cl-prolog::memberchk 'missing cycle)
               (fails-without-looping
                'cl-prolog::select 'missing cycle
                (cl-prolog:fresh-logic-variable "?REST"))
               (fails-without-looping
                'cl-prolog::nth0 8 cycle
                (cl-prolog:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog::nth1 8 cycle
                (cl-prolog:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog::last cycle
                (cl-prolog:fresh-logic-variable "?ITEM"))
               (fails-without-looping
                'cl-prolog::append cycle nil
                (cl-prolog:fresh-logic-variable "?RESULT"))
               (fails-without-looping
                'cl-prolog::reverse cycle
                (cl-prolog:fresh-logic-variable "?REVERSED"))
               (fails-without-looping
                'cl-prolog::length cycle
                (cl-prolog:fresh-logic-variable "?LENGTH"))))
      (let ((item (cl-prolog:fresh-logic-variable "?ITEM")))
        (is-equal '(a a b)
                  (mapcar (lambda (environment)
                            (cl-prolog:logic-substitute item environment))
                          (solutions 'cl-prolog::member item '(a a b)))))
      (is-equal 1 (length (solutions 'cl-prolog::member 'a self-cycle)))
      (is-equal 1 (length (solutions 'cl-prolog::member 'a two-node-cycle)))
      (is-equal 1 (length (solutions 'cl-prolog::member 'b two-node-cycle)))
      (check-cycle self-cycle)
      (check-cycle two-node-cycle)
      (is-equal 1 (length (solutions 'cl-prolog::member 'c shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog::memberchk 'c shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog::select 'a shared-list shared-tail)))
      (is-equal 1 (length (solutions 'cl-prolog::nth0 2 shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog::nth1 3 shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog::last shared-list 'c)))
      (is-equal 1 (length (solutions 'cl-prolog::is_list shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog::append shared-list nil shared-list)))
      (is-equal 1 (length (solutions 'cl-prolog::reverse shared-list '(c b a))))
      (is-equal 1 (length (solutions 'cl-prolog::length shared-list 3))))))

(deftest cyclic-copy-helpers-preserve-cycles-and-sharing ()
  (cl-prolog::%with-logic-variable-order
    (let* ((variable (cl-prolog:fresh-logic-variable "?SOURCE"))
           (cycle (cons variable nil))
           (shared (list 'shared))
           (root (cons shared shared)))
      (setf (cdr cycle) cycle)
      (let ((freshened (cl-prolog::%freshen-term
                        cycle (make-hash-table :test #'eq))))
        (is (not (eq freshened cycle)))
        (is (eq freshened (cdr freshened)))
        (is (cl-prolog:logic-var-p (car freshened)))
        (is (not (eq variable (car freshened)))))
      (let ((freshened (cl-prolog::%freshen-term
                        root (make-hash-table :test #'eq))))
        (is (eq (car freshened) (cdr freshened))))
      (let ((canonical (cl-prolog::%canonicalize-variant cycle)))
        (is (eq canonical (cdr canonical))))
      (let ((canonical (cl-prolog::%canonicalize-variant root)))
        (is (eq (car canonical) (cdr canonical)))))))

(deftest variant-instantiation-restores-shared-table-variables ()
  (cl-prolog::%with-logic-variable-order
    (let* ((variable (cl-prolog:fresh-logic-variable "?SOURCE"))
           (canonical (cl-prolog::%canonicalize-variant (list variable variable)))
           (instantiated (cl-prolog::%instantiate-variant canonical)))
      (is (cl-prolog:logic-var-p (first instantiated)))
      (is (eq (first instantiated) (second instantiated)))
      (is (not (eq variable (first instantiated)))))))

(deftest variant-instantiation-copies-a-malformed-marker-shaped-node ()
  (let ((malformed (list cl-prolog::+variant-variable-marker+ 0 'extra)))
    (is-equal malformed (cl-prolog::%instantiate-variant malformed))))

(cl-weave:it-property
    "canonicalizing an instantiated variant reproduces the same canonical form"
    ((term (let ((variables (list (cl-prolog:fresh-logic-variable "?A")
                                  (cl-prolog:fresh-logic-variable "?B")
                                  (cl-prolog:fresh-logic-variable "?C"))))
             (cl-weave:gen-recursive
              (cl-weave:gen-one-of (cl-weave:gen-integer :min -10 :max 10)
                                   (cl-weave:gen-member '(a b c))
                                   (cl-weave:gen-member variables))
              (lambda (self) (cl-weave:gen-list self :min-length 0 :max-length 3))
              :max-depth 3))))
  (cl-weave:expect-has-assertions)
  (cl-prolog::%with-logic-variable-order
    (let* ((canonical (cl-prolog::%canonicalize-variant term))
           (instantiated (cl-prolog::%instantiate-variant canonical))
           (recanonical (cl-prolog::%canonicalize-variant instantiated)))
      (cl-weave:expect recanonical :to-equal canonical))))

(deftest findall-with-cyclic-tail-terminates ()
  (cl-prolog::%with-logic-variable-order
    (let ((tail (list 'tail))
          (bag (cl-prolog:fresh-logic-variable "?BAG"))
          (resolved nil))
      (setf (cdr tail) tail)
      (funcall (cl-prolog::%goal-solver 'cl-prolog::findall 4)
               (list 'cl-prolog::findall 'template 'cl-prolog::fail bag tail)
               (make-rulebase) nil nil
               (lambda (environment)
                 (setf resolved (cl-prolog::%walk-term bag environment))))
      (is (eq tail resolved)))))
