(in-package #:cl-prolog.tests)

(deftest-queries finite-domain-relations ((make-rulebase))
  ((and (in (?x ?y) (1 |..| 3)) (|#<| ?x ?y) (labeling (ff up) (?x ?y)))
   => (((?x . 1) (?y . 2)) ((?x . 1) (?y . 3)) ((?x . 2) (?y . 3))))
  ((and (in ?x (1 2 3)) (|#\\=| ?x 2) (labeling (down) (?x)))
   => (((?x . 3)) ((?x . 1))))
  ((|#=| 2 2) :succeeds)
  ((|#=<| 2 2) :succeeds)
  ((|#>| 3 2) :succeeds)
  ((|#>=| 3 3) :succeeds)
  ((|#=| 2 3) :fails)
  ((|#\\=| 2 2) :fails)
  ((|#<| 3 2) :fails)
  ((|#>=| 2 3) :fails))

(deftest-queries finite-domain-variable-pair-propagation ((make-rulebase))
  ((and (in ?x (1 |..| 3)) (in ?y (2 |..| 4)) (|#>| ?x ?y)
        (labeling () (?x ?y)))
   => (((?x . 3) (?y . 2))))
  ((and (in ?x (1 |..| 2)) (in ?y (3 |..| 4)) (|#>=| ?x ?y)) :fails)
  ((and (in ?x (1 |..| 2)) (in ?y (2 |..| 3)) (|#=| ?x ?y)
        (labeling () (?x ?y)))
   => (((?x . 2) (?y . 2))))
  ((and (in ?x (1 |..| 1)) (in ?y (1 |..| 1)) (|#\\=| ?x ?y)) :fails)
  ((and (in (?x ?y) (1 |..| 3)) (|#<| ?x ?y)
        (labeling () (?x ?y)))
   => (((?x . 1) (?y . 2)) ((?x . 1) (?y . 3)) ((?x . 2) (?y . 3)))))

(deftest-queries finite-domain-ins-and-indomain ((make-rulebase))
  ((and (ins (?x ?y) (2 |..| 4)) (|#<| ?x ?y)
        (indomain ?x) (indomain ?y))
   => (((?x . 2) (?y . 3)) ((?x . 2) (?y . 4)) ((?x . 3) (?y . 4))))
  ((and (ins ?x (3 1 2)) (indomain ?x))
   => (((?x . 1)) ((?x . 2)) ((?x . 3))))
  ((and (ins ?x (1 |..| 1)) (|#=| ?x 2)) :fails)
  ((ins atom (1 |..| 3)) :signals)
  ((ins (?x) invalid-domain) :signals)
  ((indomain ?x) :signals)
  ((indomain 1) :signals))

(deftest-queries finite-domain-all-different-and-isolation ((make-rulebase))
  ((and (in (?x ?y) (1 |..| 2)) (all_different (?x ?y))
        (labeling (ff) (?x ?y)))
   => (((?x . 1) (?y . 2)) ((?x . 2) (?y . 1))))
  ((and (in (?x ?y) (1 |..| 1)) (all_different (?x ?y))) :fails)
  ((and (in ?x (4 |..| 4)) (labeling () (?x))) => (((?x . 4))))
  ((and (in ?x (7 |..| 7)) (labeling () (?x))) => (((?x . 7)))))

(deftest finite-domain-source-operators ()
  (is-equal '(in cl-prolog::?x (|..| 1 3))
            (read-prolog-term "X in 1..3"))
  (is-equal '(|#=| cl-prolog::?x 2)
            (read-prolog-term "X #= 2"))
  (is-equal '(|#\\=| cl-prolog::?x 2)
            (read-prolog-term "X #\\= 2")))
