;;;; Atom, character, and numeric text builtin contract.

(in-package #:cl-prolog.tests)

(deftest-queries atom-builtins ((make-rulebase))
  ((cl-prolog::atom-length cl-prolog::hello ?length) => (((?length . 5))))
  ((cl-prolog::atom-length cl-prolog::hello 5) :succeeds)
  ((cl-prolog::atom-length cl-prolog::hello 4) :fails)
  ((cl-prolog::atom-concat cl-prolog::hello cl-prolog::world ?whole)
   => (((?whole . cl-prolog::helloworld))))
  ((cl-prolog::atom-concat ?left ?right cl-prolog::abc)
   => (((?left . cl-prolog::||) (?right . cl-prolog::abc))
       ((?left . cl-prolog::a) (?right . cl-prolog::bc))
       ((?left . cl-prolog::ab) (?right . cl-prolog::c))
       ((?left . cl-prolog::abc) (?right . cl-prolog::||))))
  ((cl-prolog::atom-concat cl-prolog::a ?right cl-prolog::abc)
   => (((?right . cl-prolog::bc))))
  ((cl-prolog::sub-atom cl-prolog::abc ?before ?length ?after ?sub)
   :succeeds :limit 10)
  ((cl-prolog::sub-atom cl-prolog::abc 1 1 ?after ?sub)
   => (((?after . 1) (?sub . cl-prolog::b))))
  ((cl-prolog::atom-chars cl-prolog::abc ?chars)
   => (((?chars cl-prolog::a cl-prolog::b cl-prolog::c))))
  ((cl-prolog::atom-chars ?atom
                          (cl-prolog::a cl-prolog::b cl-prolog::c))
   => (((?atom . cl-prolog::abc))))
  ((cl-prolog::atom-codes cl-prolog::abc ?codes) => (((?codes 65 66 67))))
  ((cl-prolog::atom-codes ?atom (65 66 67)) => (((?atom . cl-prolog::abc))))
  ((cl-prolog::char-code cl-prolog::a ?code) => (((?code . 65))))
  ((cl-prolog::char-code ?character 65) => (((?character . cl-prolog::a))))
  ((cl-prolog::number-chars 42 ?chars)
   => (((?chars cl-prolog::|4| cl-prolog::|2|))))
  ((cl-prolog::number-chars ?number (cl-prolog::|4| cl-prolog::|2|))
   => (((?number . 42))))
  ((cl-prolog::number-codes -17 ?codes) => (((?codes 45 49 55))))
  ((cl-prolog::number-codes ?number (45 49 55)) => (((?number . -17)))))

(defun parse-number-codes (codes)
  (let ((solutions (query-prolog
                    (make-rulebase)
                    `(cl-prolog::number-codes ?number ,codes))))
    (cdr (assoc '?number (first solutions)))))

(defun number-codes-error-type (codes)
  (handler-case
      (progn (parse-number-codes codes) nil)
    (prolog-runtime-error (condition)
      (type-of condition))))

(defun round-trip-number-codes (number)
  (let* ((encoded (query-prolog
                   (make-rulebase)
                   `(cl-prolog::number-codes ,number ?codes)))
         (codes (cdr (assoc '?codes (first encoded)))))
    (parse-number-codes codes)))

(defun number-output-error-type (number)
  (handler-case
      (progn
        (query-prolog (make-rulebase)
                      `(cl-prolog::number-codes ,number ?codes))
        nil)
    (prolog-runtime-error (condition)
      (type-of condition))))

(deftest-table atom-number-text-grammar ()
  (:equal 0 (parse-number-codes '(48)))
  (:equal 17 (parse-number-codes '(43 49 55)))
  (:equal -17 (parse-number-codes '(45 49 55)))
  (:equal 12.5d0 (parse-number-codes '(49 50 46 53)))
  (:equal 1250.0d0 (parse-number-codes '(49 46 50 53 69 43 51)))
  (:equal 0.0125d0 (parse-number-codes '(49 46 50 53 101 45 50)))
  (:equal 'prolog-domain-error (number-codes-error-type '(49 47 50)))
  (:equal 'prolog-domain-error (number-codes-error-type '(49 46)))
  (:equal 'prolog-domain-error (number-codes-error-type '(46 53)))
  (:equal 'prolog-domain-error (number-codes-error-type '(49 101)))
  (:equal 'prolog-domain-error (number-codes-error-type '(49 50 120))))

(deftest-table atom-number-text-round-trips ()
  (:equal 42 (round-trip-number-codes 42))
  (:equal 12.5d0 (round-trip-number-codes 12.5d0))
  (:equal -0.125d0 (round-trip-number-codes -0.125d0))
  (:equal 1.25d20 (round-trip-number-codes 1.25d20))
  (:equal 1.25d-20 (round-trip-number-codes 1.25d-20))
  (:equal 'prolog-domain-error
          (number-output-error-type 1/2)))

(deftest atom-list-conversion-rejects-cycles ()
  (let ((cycle (list (cl-prolog::%text-atom "a"))))
    (setf (cdr cycle) cycle)
    (handler-case
        (progn
          (cl-prolog::%character-list-text
           cycle nil (cl-prolog::%iso-atom "ATOM_CHARS"))
          (error "Expected cyclic list rejection"))
      (prolog-type-error (condition)
        (declare (ignore condition))
        (is t "Cyclic lists must raise a Prolog type error")))))

(defun normalize-atom-error-data (term)
  (typecase term
    (null nil)
    (symbol (symbol-name term))
    (cons (mapcar #'normalize-atom-error-data term))
    (t term)))

(defun atom-builtin-error-summary (goal)
  (handler-case
      (progn (query-prolog (make-rulebase) goal) nil)
    (prolog-runtime-error (condition)
      (list (type-of condition)
            (normalize-atom-error-data
             (second (prolog-exception-term condition)))))))

(deftest-table atom-builtins-report-iso-errors ()
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (atom-builtin-error-summary '(cl-prolog::atom-length ?atom ?length)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 1))
          (atom-builtin-error-summary '(cl-prolog::atom-length 1 ?length)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (atom-builtin-error-summary '(cl-prolog::atom-length atom -1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (atom-builtin-error-summary '(cl-prolog::atom-concat ?a right ?whole)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 3))
          (atom-builtin-error-summary '(cl-prolog::atom-concat 3 right whole)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (atom-builtin-error-summary '(cl-prolog::sub-atom ?atom 0 1 ?after ?sub)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.5))
          (atom-builtin-error-summary '(cl-prolog::sub-atom abc 1.5 1 ?after ?sub)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (atom-builtin-error-summary '(cl-prolog::atom-chars ?atom ?chars)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "CHARACTER" "AB"))
          (atom-builtin-error-summary '(cl-prolog::atom-chars ?atom (ab))))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" "ATOM"))
          (atom-builtin-error-summary '(cl-prolog::atom-codes ?atom (atom))))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (atom-builtin-error-summary '(cl-prolog::char-code ?character ?code)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "CHARACTER" "AB"))
          (atom-builtin-error-summary '(cl-prolog::char-code ab ?code)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "CHARACTER_CODE" -1))
          (atom-builtin-error-summary '(cl-prolog::char-code ?character -1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "NUMBER" "ATOM"))
          (atom-builtin-error-summary '(cl-prolog::number-chars atom ?chars)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NUMBER_TEXT" "bad"))
          (atom-builtin-error-summary '(cl-prolog::number-codes ?number (98 97 100)))))
