(in-package #:cl-prolog.tests)

(deftest-queries term-builtins ((make-rulebase))
  ((cl-prolog::var ?x) :succeeds)
  ((and (= ?x value) (cl-prolog::var ?x)) :fails)
  ((cl-prolog::nonvar value) :succeeds)
  ((cl-prolog::nonvar ?x) :fails)
  ((cl-prolog::atom value) :succeeds)
  ((cl-prolog::atom 3) :fails)
  ((cl-prolog:atomic value) :succeeds)
  ((cl-prolog:atomic 3/2) :succeeds)
  ((cl-prolog:atomic ?x) :fails)
  ((cl-prolog:atomic (node value)) :fails)
  ((cl-prolog:atomic "value") :fails)
  ((cl-prolog::number 3/2) :succeeds)
  ((cl-prolog::number value) :fails)
  ((cl-prolog::integer 3) :succeeds)
  ((cl-prolog::integer 3/2) :fails)
  ((cl-prolog:float 1.0) :succeeds)
  ((cl-prolog:float 1) :fails)
  ((cl-prolog:float ?x) :fails)
  ((and (= ?x 1.0d0) (cl-prolog:float ?x)) :succeeds)
  ((cl-prolog::== value value) :succeeds)
  ((cl-prolog::== ?x ?x) :succeeds)
  ((cl-prolog::== ?x ?y) :fails)
  ((and (cl-prolog::|\\==| ?x ?y) (= ?x ?y)) :succeeds)
  ((cl-prolog::|\\==| (node ?x) (node ?x)) :fails)
  ((cl-prolog::@< ?x atom) :succeeds)
  ((cl-prolog::@< 2 atom) :succeeds)
  ((cl-prolog::@< atom (node)) :succeeds)
  ((cl-prolog::@< (a x) (b x)) :succeeds)
  ((cl-prolog::@=< (node left) (node left)) :succeeds)
  ((cl-prolog::@> (node right) atom) :succeeds)
  ((cl-prolog::@>= 2 2) :succeeds)
  ((cl-prolog::compare ?order 1 2) => (((?order . <))))
  ((cl-prolog::compare ?order 1 1.0) => (((?order . <))))
  ((cl-prolog::compare ?order 1.0 1) => (((?order . >))))
  ((cl-prolog::compare ?order value value) => (((?order . =))))
  ((cl-prolog::compare ?order (node) value) => (((?order . >))))
  ((cl-prolog::term-variables (pair ?x (nested ?y ?x)) ?variables)
   => (((?x . ?x) (?y . ?y) (?variables ?x ?y))))
  ((and (= ?x bound)
        (cl-prolog::term-variables (pair ?x ?y) ?variables))
   => (((?x . bound) (?y . ?y) (?variables ?y))))
  ((cl-prolog::compound (node left right)) :succeeds)
  ((cl-prolog::compound value) :fails)
  ((cl-prolog:callable value) :succeeds)
  ((cl-prolog:callable nil) :succeeds)
  ((cl-prolog:callable (node left right)) :succeeds)
  ((cl-prolog:callable ?x) :fails)
  ((cl-prolog:callable 3) :fails)
  ((cl-prolog:callable "node") :fails)
  ((and (= ?goal (node left)) (cl-prolog:callable ?goal)) :succeeds)
  ((cl-prolog::ground (node left 3)) :succeeds)
  ((cl-prolog::ground (node ?x 3)) :fails)
  ((cl-prolog::functor (node left right) ?name ?arity)
   => (((?name . node) (?arity . 2))))
  ((cl-prolog::functor value ?name ?arity)
   => (((?name . value) (?arity . 0))))
  ((cl-prolog::functor ?term node 2) :succeeds)
  ((cl-prolog::functor ?term 7 0) => (((?term . 7))))
  ((cl-prolog::arg 2 (node left right) ?value)
   => (((?value . right))))
  ((cl-prolog::arg 0 (node left right) ?value) :fails)
  ((cl-prolog::arg 3 (node left right) ?value) :fails)
  ((and (cl-prolog::copy-term (pair ?x ?x) ?copy)
        (= ?copy (pair copied copied)))
   :succeeds)
  ((and (cl-prolog::copy-term (pair ?x ?x) ?copy)
        (= ?copy (pair left right)))
   :fails)
  ((cl-prolog:numbervars (pair ?x ?x ?y) 3 ?end)
   => (((?x cl-prolog::$var 3)
        (?y cl-prolog::$var 4)
        (?end . 5))))
  ((and (= ?x bound)
        (cl-prolog:numbervars (pair ?x ?y) 0 ?end))
   => (((?x . bound) (?y cl-prolog::$var 0) (?end . 1))))
  ((cl-prolog::|=..| (node left right) ?list)
   => (((?list node left right))))
  ((cl-prolog::|=..| value ?list)
   => (((?list value))))
  ((cl-prolog::|=..| ?term (node left right))
   => (((?term node left right))))
  ((cl-prolog::|=..| ?term (value))
   => (((?term . value)))))

(defun normalize-iso-error-data (term)
  (typecase term
    (null nil)
    (symbol (symbol-name term))
    (cons (mapcar #'normalize-iso-error-data term))
    (t term)))

(defun term-builtin-error-summary (goal)
  (handler-case
      (progn
        (query-prolog (make-rulebase) goal)
        nil)
    (prolog-runtime-error (condition)
      (list (type-of condition)
            (normalize-iso-error-data
             (second (prolog-exception-term condition)))))))

(deftest-table term-builtins-report-iso-errors ()
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::functor ?term ?name 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::functor ?term node ?arity)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOMIC" ("BAD" "NAME")))
          (term-builtin-error-summary '(cl-prolog::functor ?term (bad name) 1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog::functor ?term node 1.0)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog::functor ?term node -1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (term-builtin-error-summary '(cl-prolog::functor ?term 7 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::arg ?index (node value) ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog::arg 1.0 (node value) ?value)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog::arg -1 (node value) ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::arg 1 ?term ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "COMPOUND" "ATOM"))
          (term-builtin-error-summary '(cl-prolog::arg 1 atom ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog:numbervars (pair ?x) ?start ?end)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (term-builtin-error-summary '(cl-prolog:numbervars (pair ?x) 1.0 ?end)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (term-builtin-error-summary '(cl-prolog:numbervars (pair ?x) -1 ?end)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::|=..| ?term ?list)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "LIST" "IMPROPER"))
          (term-builtin-error-summary '(cl-prolog::|=..| ?term improper)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NON_EMPTY_LIST" nil))
          (term-builtin-error-summary '(cl-prolog::|=..| ?term nil)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (term-builtin-error-summary '(cl-prolog::|=..| ?term (?head value))))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (term-builtin-error-summary '(cl-prolog::|=..| ?term (7 value)))))

(deftest term-order-properties ()
  (let ((terms '(?x -3 1 1.0 3/2 alpha beta (node) (node left))))
    (dolist (left terms)
      (dolist (right terms)
        (let ((forward (cl-prolog::%compare-terms left right))
              (reverse (cl-prolog::%compare-terms right left)))
          (is (= forward (- reverse)))
          (is (member forward '(-1 0 1)))
          (is (eq (zerop forward)
                  (prolog-succeeds-p
                   (make-rulebase)
                   `(cl-prolog:compare = ,left ,right))))
          (is (eq (minusp forward)
                  (prolog-succeeds-p
                   (make-rulebase)
                   `(cl-prolog:@< ,left ,right))))
          (is (eq (plusp forward)
                  (prolog-succeeds-p
                   (make-rulebase)
                   `(cl-prolog:@> ,left ,right)))))))))
