(in-package #:cl-prolog.tests)

(deftest-queries term-builtins ((make-rulebase))
  ((cl-prolog::var ?x) :succeeds)
  ((and (= ?x value) (cl-prolog::var ?x)) :fails)
  ((cl-prolog::nonvar value) :succeeds)
  ((cl-prolog::nonvar ?x) :fails)
  ((cl-prolog::atom value) :succeeds)
  ((cl-prolog::atom 3) :fails)
  ((cl-prolog:atomic value) :succeeds)
  ((cl-prolog:atomic 3/2) :fails)
  ((cl-prolog:atomic #C(1 2)) :fails)
  ((cl-prolog:atomic ?x) :fails)
  ((cl-prolog:atomic (node value)) :fails)
  ((cl-prolog:atomic "value") :fails)
  ((cl-prolog::number 3/2) :fails)
  ((cl-prolog::number #C(1 2)) :fails)
  ((cl-prolog::number value) :fails)
  ((cl-prolog::integer 3) :succeeds)
  ((cl-prolog::integer 3/2) :fails)
  ((cl-prolog:float 1.0) :succeeds)
  ((cl-prolog:float 1) :fails)
  ((cl-prolog:float ?x) :fails)
  ((and (= ?x 1.0d0) (cl-prolog:float ?x)) :succeeds)
  ((cl-prolog::== value value) :succeeds)
  ((cl-prolog::== ?x ?x) :succeeds)
  ((cl-prolog::== ?x ?y) :fails)
  ((and (cl-prolog::|\\==| ?x ?y) (= ?x ?y)) :succeeds)
  ((cl-prolog::|\\==| (node ?x) (node ?x)) :fails)
  ((cl-prolog::|=@=| (pair ?x ?x) (pair ?y ?y)) :succeeds)
  ((cl-prolog::|=@=| (pair ?x ?x) (pair ?y ?z)) :fails)
  ((cl-prolog::|\\=@=| (pair ?x ?x) (pair ?y ?z)) :succeeds)
  ((and (cl-prolog::|=@=| (pair ?x ?x) (pair ?y ?y))
        (cl-prolog::var ?x)
        (cl-prolog::var ?y))
   :succeeds)
  ((cl-prolog::@< ?x atom) :succeeds)
  ((cl-prolog::@< 2 atom) :succeeds)
  ((cl-prolog::@< atom (node)) :succeeds)
  ((cl-prolog::@< (a x) (b x)) :succeeds)
  ((cl-prolog::@=< (node left) (node left)) :succeeds)
  ((cl-prolog::@> (node right) atom) :succeeds)
  ((cl-prolog::@>= 2 2) :succeeds)
  ((cl-prolog::compare ?order 1 2) => (((?order . <))))
  ((cl-prolog::compare ?order 1 1.0) => (((?order . <))))
  ((cl-prolog::compare ?order 1.0 1) => (((?order . >))))
  ((cl-prolog::compare ?order value value) => (((?order . =))))
  ((cl-prolog::compare ?order (node) value) => (((?order . >))))
  ((and (cl-prolog:unifiable (node ?x) (node value) ?unifier)
        (cl-prolog::var ?x))
   => (((?x . ?x) (?unifier (= ?x value)))))
  ((cl-prolog:unifiable (pair ?y ?x) (pair left right) ?unifier)
   => (((?y . ?y)
        (?x . ?x)
        (?unifier (= ?y left) (= ?x right)))))
  ((cl-prolog:unifiable (pair ?x ?x) (pair value value) ?unifier)
   => (((?x . ?x) (?unifier (= ?x value)))))
  ((cl-prolog:unifiable (pair ?x ?x) (pair ?y value) ?unifier)
   => (((?x . ?x)
        (?y . ?y)
        (?unifier (= ?x ?y) (= ?y value)))))
  ((cl-prolog:unifiable (pair ?x ?x) (pair left right) ?unifier) :fails)
  ((cl-prolog:unifiable ?x (node ?x) ?unifier) :fails)
  ((and (cl-prolog::subsumes_term (node ?general) (node value))
        (cl-prolog::var ?general))
   :succeeds)
  ((cl-prolog::subsumes_term (pair ?x ?x) (pair same same)) :succeeds)
  ((cl-prolog::subsumes_term (pair ?x ?x) (pair left right)) :fails)
  ((cl-prolog::subsumes_term (node value) (node ?specific)) :fails)
  ((cl-prolog::subsumes_term ?term (node ?specific)) :succeeds)
  ((cl-prolog::term_variables (pair ?x (nested ?y ?x)) ?variables)
   => (((?x . ?x) (?y . ?y) (?variables ?x ?y))))
  ((and (= ?x bound)
        (cl-prolog::term_variables (pair ?x ?y) ?variables))
   => (((?x . bound) (?y . ?y) (?variables ?y))))
  ((cl-prolog::term_variables (pair ?x ?y ?x) ?variables (end))
   => (((?x . ?x) (?y . ?y) (?variables ?x ?y end))))
  ((or (and (cl-prolog::term_variables (pair ?x ?y) (?x))
            (= ?result leaked))
       (and (cl-prolog::var ?x)
            (cl-prolog::var ?y)
            (= ?result preserved)))
   => (((?x . ?x) (?y . ?y) (?result . preserved))))
  ((cl-prolog::compound (node left right)) :succeeds)
  ((cl-prolog::compound value) :fails)
  ((cl-prolog:callable value) :succeeds)
  ((cl-prolog:callable nil) :succeeds)
  ((cl-prolog:callable (node left right)) :succeeds)
  ((cl-prolog:callable ?x) :fails)
  ((cl-prolog:callable 3) :fails)
  ((cl-prolog:callable "node") :fails)
  ((and (= ?goal (node left)) (cl-prolog:callable ?goal)) :succeeds)
  ((cl-prolog::ground (node left 3)) :succeeds)
  ((cl-prolog::ground (node ?x 3)) :fails)
  ((cl-prolog:acyclic_term (node ?x (leaf value))) :succeeds)
  ((cl-prolog:cyclic_term (node ?x (leaf value))) :fails)
  ((cl-prolog::functor (node left right) ?name ?arity)
   => (((?name . node) (?arity . 2))))
  ((cl-prolog::functor value ?name ?arity)
   => (((?name . value) (?arity . 0))))
  ((cl-prolog::functor ?term node 2) :succeeds)
  ((cl-prolog::functor ?term 7 0) => (((?term . 7))))
  ((cl-prolog::arg 2 (node left right) ?value)
   => (((?value . right))))
  ((cl-prolog::arg 0 (node left right) ?value) :fails)
  ((cl-prolog::arg 3 (node left right) ?value) :fails)
  ((and (cl-prolog::copy_term (pair ?x ?x) ?copy)
        (= ?copy (pair copied copied)))
   :succeeds)
  ((and (cl-prolog::copy_term (pair ?x ?x) ?copy)
        (= ?copy (pair left right)))
   :fails)
  ((or (and (cl-prolog::copy_term (pair ?x ?x) ?copy)
            (= ?copy (pair left right)))
       (and (cl-prolog::var ?x)
            (cl-prolog::var ?copy)
            (= ?result preserved)))
   => (((?x . ?x) (?copy . ?copy) (?result . preserved))))
  ((cl-prolog:numbervars (pair ?x ?x ?y) 3 ?end)
   => (((?x cl-prolog::$var 3)
        (?y cl-prolog::$var 4)
        (?end . 5))))
  ((and (= ?x bound)
        (cl-prolog:numbervars (pair ?x ?y) 0 ?end))
   => (((?x . bound) (?y cl-prolog::$var 0) (?end . 1))))
  ((or (and (cl-prolog:numbervars (pair ?x ?y) 0 1)
            (= ?result leaked))
       (and (cl-prolog::var ?x)
            (cl-prolog::var ?y)
            (= ?result preserved)))
   => (((?x . ?x) (?y . ?y) (?result . preserved))))
  ((cl-prolog::|=..| (node left right) ?list)
   => (((?list node left right))))
  ((cl-prolog::|=..| value ?list)
   => (((?list value))))
  ((cl-prolog::|=..| ?term (node left right))
   => (((?term node left right))))
  ((cl-prolog::|=..| ?term (value))
   => (((?term . value)))))

(deftest cyclic-term-detection-handles-circular-and-shared-conses ()
  (let* ((shared (list 'leaf 'value))
         (acyclic (list 'pair shared shared))
         (car-cycle (list 'node))
         (cdr-cycle (list 'node)))
    (setf (car car-cycle) car-cycle
          (cdr cdr-cycle) cdr-cycle)
    (is (cl-prolog::%term-acyclic-p acyclic))
    (is (not (cl-prolog::%term-acyclic-p car-cycle)))
    (is (not (cl-prolog::%term-acyclic-p cdr-cycle)))
    (is (not (cl-prolog::%term-acyclic-p
              '?cycle '((?cycle node ?cycle)))))))

(deftest-table term-builtins-report-iso-errors ()
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::functor ?term ?name 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::functor ?term node ?arity)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOMIC" ("BAD" "NAME")))
          (builtin-error-summary '(cl-prolog::functor ?term (bad name) 1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (builtin-error-summary '(cl-prolog::functor ?term node 1.0)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (builtin-error-summary '(cl-prolog::functor ?term node -1)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (builtin-error-summary '(cl-prolog::functor ?term 7 1)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::arg ?index (node value) ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (builtin-error-summary '(cl-prolog::arg 1.0 (node value) ?value)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (builtin-error-summary '(cl-prolog::arg -1 (node value) ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::arg 1 ?term ?value)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "COMPOUND" "ATOM"))
          (builtin-error-summary '(cl-prolog::arg 1 atom ?value)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog:numbervars (pair ?x) ?start ?end)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "INTEGER" 1.0))
          (builtin-error-summary '(cl-prolog:numbervars (pair ?x) 1.0 ?end)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NOT_LESS_THAN_ZERO" -1))
          (builtin-error-summary '(cl-prolog:numbervars (pair ?x) -1 ?end)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::|=..| ?term ?list)))
  (:equal '(prolog-type-error ("TYPE_ERROR" "LIST" "IMPROPER"))
          (builtin-error-summary '(cl-prolog::|=..| ?term improper)))
  (:equal '(prolog-domain-error ("DOMAIN_ERROR" "NON_EMPTY_LIST" nil))
          (builtin-error-summary '(cl-prolog::|=..| ?term nil)))
  (:equal '(prolog-instantiation-error "INSTANTIATION_ERROR")
          (builtin-error-summary '(cl-prolog::|=..| ?term (?head value))))
  (:equal '(prolog-type-error ("TYPE_ERROR" "ATOM" 7))
          (builtin-error-summary '(cl-prolog::|=..| ?term (7 value)))))

(deftest term-order-properties ()
  (cl-prolog::%with-logic-variable-order
    (let ((terms (list (cl-prolog:fresh-logic-variable "?Z")
                       -3 1 1.0 3/2 'alpha 'beta '(node) '(node left))))
      (dolist (left terms)
        (dolist (right terms)
          (let ((forward (cl-prolog::%compare-terms left right))
                (reverse (cl-prolog::%compare-terms right left)))
            (is (= forward (- reverse)))
            (is (member forward '(-1 0 1)))))))))

(deftest host-only-numbers-are-not-prolog-numbers ()
  (dolist (number (list 3/2 #C(1 2)))
    (is (not (cl-prolog::%prolog-number-p number)))
    (is (= 4 (cl-prolog::%term-order-class number))))
  (dolist (number (list 1 1.0))
    (is (cl-prolog::%prolog-number-p number))
    (is (= 1 (cl-prolog::%term-order-class number)))))

(deftest cyclic-term-identity-variants-and-order ()
  (let ((left (cons 'node nil))
        (right (cons 'node nil))
        (different (cons 'other nil)))
    (setf (cdr left) left
          (cdr right) right
          (cdr different) different)
    (is (cl-prolog::%term-identical-p left right))
    (is (not (cl-prolog::%term-identical-p left different)))
    (is (cl-prolog::%term-variant-p left right))
    (let ((forward (cl-prolog::%compare-terms left different))
          (reverse (cl-prolog::%compare-terms different left)))
      (is (member forward '(-1 1)))
      (is (= forward (- reverse))))))

(deftest term-order-distinguishes-packages-for-equal-symbol-names ()
  (let* ((name "PACKAGE-SENSITIVE-ATOM")
         (left (intern name (find-package '#:cl-prolog)))
         (right (intern name (find-package '#:cl-prolog.tests)))
         (forward (cl-prolog::%compare-terms left right))
         (reverse (cl-prolog::%compare-terms right left)))
    (is (member forward '(-1 1)))
    (is (= forward (- reverse)))))

(deftest term-order-distinguishes-uninterned-equal-name-atoms ()
  (let* ((left (make-symbol "SAME-NAME-ATOM"))
         (right (make-symbol "SAME-NAME-ATOM"))
         (forward (cl-prolog::%compare-terms left right))
         (reverse (cl-prolog::%compare-terms right left)))
    (is (member forward '(-1 1)))
    (is (= forward (- reverse)))
    (is (= forward (cl-prolog::%compare-terms left right)))))

(deftest term-order-uses-variable-creation-order ()
  (cl-prolog::%with-logic-variable-order
    (let ((first (cl-prolog:fresh-logic-variable "?Z"))
          (second (cl-prolog:fresh-logic-variable "?A")))
      (is (= -1 (cl-prolog::%compare-terms first second)))
      (is (= 1 (cl-prolog::%compare-terms second first))))))
