(in-package #:cl-prolog.tests)

(deftest-table arithmetic-functions-validate-indicators-before-arguments ()
  (:equal
   (list (cl-prolog::%iso-atom "TYPE_ERROR")
         (cl-prolog::%iso-atom "EVALUABLE")
         (cl-prolog::%iso-term "/" 'unknown 1))
   (arithmetic-type-error-formal '(unknown 1)))
  (:equal
   (list (cl-prolog::%iso-atom "TYPE_ERROR")
         (cl-prolog::%iso-atom "EVALUABLE")
         (cl-prolog::%iso-term "/" '+ 3))
   (arithmetic-type-error-formal '(+ 1 2 3)))
  (:equal
   (list (cl-prolog::%iso-atom "TYPE_ERROR")
         (cl-prolog::%iso-atom "EVALUABLE")
         (cl-prolog::%iso-term "/" 'unknown 1))
   (arithmetic-type-error-formal '(unknown ?unbound))))

(defun arithmetic-type-error-formal (expression)
  (handler-case
      (progn
        (query-prolog (make-rulebase) (list 'is '?result expression))
        (error "Expected an arithmetic type error for ~S" expression))
    (prolog-type-error (condition)
      (second (prolog-exception-term condition)))))

(deftest arithmetic-rejects-host-only-ratio-input ()
  (signals-error
    (query-prolog (make-rulebase) (list 'is '?result 1/2))))

(deftest-queries arithmetic-builtins ((make-rulebase))
  ((is ?x (+ 2 (* 3 4)))         => (((?x . 14))))
  ((is ?x (- 5))                 => (((?x . -5))))
  ((is ?x (- 10 3))              => (((?x . 7))))
  ((is ?x (/ 7 2))               => (((?x . 3.5d0))))
  ((is ?x (/ 1 2))               => (((?x . 0.5d0))))
  ((is ?x (mod 17 5))            => (((?x . 2))))
  ((is ?x (abs -9))              => (((?x . 9))))
  ((is ?x (// -7 3))             => (((?x . -2))))
  ((is ?x (div -7 3))            => (((?x . -3))))
  ((is ?x (rem -7 3))            => (((?x . -1))))
  ((is ?x (mod -7 3))            => (((?x . 2))))
  ((is ?x (sign -7))             => (((?x . -1))))
  ((is ?x (min 7 3))             => (((?x . 3))))
  ((is ?x (max 7 3))             => (((?x . 7))))
  ((is ?x (floor (/ 7 3)))       => (((?x . 2))))
  ((is ?x (ceiling (/ 7 3)))     => (((?x . 3))))
  ((is ?x (truncate (/ -7 3)))   => (((?x . -2))))
  ((is ?x (round (/ 5 2)))       => (((?x . 2))))
  ((is ?x (** 2 8))              => (((?x . 256))))
  ((is ?x (^ 3 3))               => (((?x . 27))))
  ((is ?x (+ 3))                 => (((?x . 3))))
  ((is ?x (|/\\| 6 3))          => (((?x . 2))))
  ((is ?x (|\\/| 4 3))          => (((?x . 7))))
  ((is ?x (xor 6 3))             => (((?x . 5))))
  ((is ?x (|\\| 0))             => (((?x . -1))))
  ((is ?x (|<<| 3 4))           => (((?x . 48))))
  ((is ?x (|>>| -16 2))         => (((?x . -4))))
  ((is ?x (float 3))            => (((?x . 3.0d0))))
  ((is ?x (float_integer_part -2.75d0)) => (((?x . -2.0d0))))
  ((is ?x (float_fractional_part -2.75d0)) => (((?x . -0.75d0))))
  ((is ?x signum)                :signals)
  ((is ?x (signum 9))           => (((?x . 1))))
  ((|=:=| pi 3.141592653589793d0) :succeeds)
  ((|=:=| (sqrt 9) 3)            :succeeds)
  ((|=:=| (exp 0) 1)             :succeeds)
  ((|=:=| (log 1) 0)             :succeeds)
  ((|=:=| (sin 0) 0)             :succeeds)
  ((|=:=| (cos 0) 1)             :succeeds)
  ((|=:=| (tan 0) 0)             :succeeds)
  ((|=:=| (asin 0) 0)            :succeeds)
  ((|=:=| (acos 1) 0)            :succeeds)
  ((|=:=| (atan 0) 0)            :succeeds)
  ((|=:=| (atan 0 -1) pi)        :succeeds)
  ((is 3 (+ 1 2))                :succeeds)
  ((is 4 (+ 1 2))                :fails)
  ((|=:=| (+ 1 2) 3)             :succeeds)
  ((|=:=| 3 4)                   :fails)
  ((|=\\=| 3 4)                  :succeeds)
  ((|=\\=| 3 (+ 1 2))            :fails)
  ((< 2 3)                       :succeeds)
  ((< 3 2)                       :fails)
  ((=< 3 3)                      :succeeds)
  ((> 4 3)                       :succeeds)
  ((>= 4 4)                      :succeeds)
  ((cl-prolog::between 2 4 ?x)   => (((?x . 2)) ((?x . 3)) ((?x . 4))))
  ((cl-prolog::between -2 0 ?x)  => (((?x . -2)) ((?x . -1)) ((?x . 0))))
  ((cl-prolog::between 2 4 3)    :succeeds)
  ((cl-prolog::between 2 4 5)    :fails)
  ((cl-prolog::between 4 2 ?x)   :fails)
  ((cl-prolog::succ 2 ?x)        => (((?x . 3))))
  ((cl-prolog::succ ?x 3)        => (((?x . 2))))
  ((cl-prolog::succ 2 3)         :succeeds)
  ((cl-prolog::succ 2 4)         :fails)
  ((cl-prolog::succ ?x 0)        :fails)
  ((cl-prolog::between ?low 4 ?x) :signals)
  ((cl-prolog::between 1 4.0 ?x) :signals)
  ((cl-prolog::between 1 4 atom) :signals)
  ((cl-prolog::succ ?x ?y)       :signals)
  ((cl-prolog::succ -1 ?x)       :signals)
  ((cl-prolog::succ ?x -1)       :signals)
  ((cl-prolog::succ 1.0 ?x)      :signals)
  ((and (= ?x 4) (is ?y (+ ?x 1))) => (((?x . 4) (?y . 5))))
  ((is ?x (+ ?unbound 1))        :signals)
  ((is ?x (+ atom 1))            :signals)
  ((is ?x (/ 1 0))               :signals)
  ((is ?x (// 1 0))              :signals)
  ((is ?x (rem 1.0 2))           :signals)
  ((is ?x (mod 1 0))             :signals)
  ((is ?x (sqrt -1))             :signals)
  ((is ?x (** -1 0.5d0))        :signals)
  ((is ?x (log 0))               :signals)
  ((is ?x (|/\\| 1.0 1))        :signals)
  ((is ?x (|<<| 1 1.5))         :signals))
