;;;; Query-oriented engine and builtin behavior tests.

(in-package #:cl-prolog.tests)

(deftest-queries family-relations ((make-family-rulebase))
  ((ancestor tom ?who)           => (((?who . bob)) ((?who . alice)) ((?who . eve))))
  ((ancestor ?x eve)             :set (((?x . tom)) ((?x . bob)) ((?x . alice))))
  ((ancestor ?x bob)             :first ((?x . tom)))
  ((grandparent tom ?z)          => (((?z . alice))))
  ((ancestor tom eve)            :succeeds)
  ((ancestor eve tom)            :fails)
  ((adult ?x)                    :set (((?x . tom)) ((?x . bob)) ((?x . alice)))))

(deftest-queries control-flow-builtins ((make-family-rulebase))
  ((true)                        => (nil))
  ((cl-prolog::fail)             :fails)
  ((cl-prolog::false)            :fails)
  ((= ?x left)                   => (((?x . left))))
  ((= left right)                :fails)
  ((/= tom alice)                => (nil))
  ((/= ?x ?y)                    :fails)
  ((/= tom alice)                :succeeds)
  ((!= tom alice)                => (nil))
  ((!= ?x ?y)                    :fails)
  ((!= tom alice)                :succeeds)
  ((not (parent alice tom))      => (nil))
  ((not (parent tom bob))        :fails)
  ((and (= ?goal (parent alice tom)) (not ?goal))
                                   => (((?goal parent alice tom))))
  ((and (= ?goal (parent tom bob)) (not ?goal)) :fails)
  ((cl-prolog::|\+| (parent alice tom)) => (nil))
  ((cl-prolog::|\+| (parent tom bob)) :fails)
  ((and)                         => (nil))
  ((and (parent tom bob) (parent bob alice)) => (nil))
  ((and (parent tom ?x) (parent ?x alice))   => (((?x . bob))))
  ((or (= ?x left) (= ?x right)) :set (((?x . left)) ((?x . right))))
  ((or)                          :fails)
  ((or (parent eve ?x))          :fails)
  ((call (choice ?x))            => (((?x . left)) ((?x . right))))
  ((if-then-else (choice ?x) (= ?side selected) (= ?side fallback))
                                   => (((?x . left) (?side . selected))))
  ((if-then-else fail (= ?side selected) (= ?side fallback))
                                   => (((?side . fallback))))
  ((soft-if-then-else (choice ?x) (= ?side selected) (= ?side fallback))
                                   => (((?x . left) (?side . selected))
                                       ((?x . right) (?side . selected))))
  ((soft-if-then-else fail (= ?side selected) (= ?side fallback))
                                   => (((?side . fallback))))
  ((call choice ?x)              => (((?x . left)) ((?x . right))))
  ((call parent tom ?child)      => (((?child . bob))))
  ((call (parent tom) ?child)    => (((?child . bob))))
  ((and (= ?closure (parent tom)) (call ?closure ?child))
                                   => (((?closure parent tom) (?child . bob))))
  ((call ?unbound argument)      :signals)
  ((call 42 argument)            :signals)
  ((and (= ?goal (choice ?x)) (call ?goal))
                                   => (((?goal choice left) (?x . left))
                                       ((?goal choice right) (?x . right))))
  ((once (choice ?x))            => (((?x . left))))
  ((once (parent nobody ?x))     :fails)
  ((catch (throw ball) ball (= ?x recovered))
                                   => (((?x . recovered))))
  ((catch (and (= ?x bound) (throw (problem ?x)))
           (problem ?value)
           (= ?result ?value))
                                   => (((?x . bound) (?value . bound)
                                        (?result . bound))))
  ((catch (catch (throw inner) outer fail)
           inner
           (= ?x caught-outside))
                                   => (((?x . caught-outside))))
  ((catch (throw mismatch) expected true) :signals)
  ((throw ?unbound)              :signals)
  ((repeat)                      => (nil nil nil) :limit 3))

(deftest-queries solution-collection-builtins
    ((make-rulebase
      :clauses (list (make-clause '(edge a 2))
                     (make-clause '(edge a 1))
                     (make-clause '(edge a 2))
                     (make-clause '(edge b 3)))))
  ((findall ?value (edge a ?value) ?bag)
                                   => (((?value . ?value) (?bag 2 1 2))))
  ((findall ?value (edge missing ?value) ?bag)
                                   => (((?value . ?value) (?bag))))
  ((bagof ?value (edge ?key ?value) ?bag)
                                   => (((?value . ?value) (?key . a) (?bag 2 1 2))
                                       ((?value . ?value) (?key . b) (?bag 3))))
  ((bagof ?value (^ ?key (edge ?key ?value)) ?bag)
                                   => (((?value . ?value) (?key . ?key)
                                        (?bag 2 1 2 3))))
  ((bagof ?value (edge missing ?value) ?bag) :fails)
  ((setof ?value (edge ?key ?value) ?bag)
                                   => (((?value . ?value) (?key . a) (?bag 1 2))
                                       ((?value . ?value) (?key . b) (?bag 3))))
  ((setof ?value (edge missing ?value) ?bag) :fails))

(deftest dynamic-database-builtins ()
  (let ((rulebase (make-rulebase)))
    (rulebase-insert-clause! rulebase (make-clause '(ordered first)))
    (rulebase-insert-clause! rulebase (make-clause '(ordered second)))
    (assert-query rulebase (ordered ?value)
                  => (((?value . first)) ((?value . second))))
    (assert-query rulebase (assertz (color apple red)) :succeeds)
    (assert-query rulebase (assertz (color apple blue)) :succeeds)
    (assert-query rulebase (asserta (color apple green)) :succeeds)
    (assert-query rulebase (color apple ?shade)
                  => (((?shade . green)) ((?shade . red)) ((?shade . blue))))
    (assert-query rulebase
                  (assertz (:- (warm ?x) (color ?x red))) :succeeds)
    (assert-query rulebase (warm apple) :succeeds)
    (assert-query rulebase (clause (color apple red) ?body)
                  => (((?body . true))))
    (assert-query rulebase (clause (warm apple) (color apple red)) :succeeds)
    (assert-query rulebase (retract (color apple ?shade))
                  :first ((?shade . green)))
    (assert-query rulebase (color apple ?shade)
                  => (((?shade . red)) ((?shade . blue))))
    (assert-query rulebase (current-predicate ?indicator)
                  => (((?indicator ordered / 1))
                      ((?indicator color / 2))
                      ((?indicator warm / 1))))
    (assert-query rulebase (retractall (color apple ?shade)) :succeeds)
    (assert-query rulebase (color apple ?shade) :fails)
    (assert-query rulebase (retractall (color apple ?shade)) :succeeds)
    (assert-query rulebase (assertz (color pear green)) :succeeds)
    (assert-query rulebase (assertz (color apple red)) :succeeds)
    (assert-query rulebase (retractall (color ?fruit ?shade)) :succeeds)
    (assert-query rulebase (color ?fruit ?shade) :fails)
    (assert-query rulebase (assertz (color apple red)) :succeeds)
    (assert-query rulebase (assertz (color pear green)) :succeeds)
    (assert-query rulebase (abolish (color / 2)) :succeeds)
    (assert-query rulebase (color apple ?shade) :fails)
    (assert-query rulebase (assertz (= left left)) :signals)
    (assert-query rulebase (clause (= left left) ?body) :signals)
    (assert-query rulebase (abolish (= / 2)) :signals)))

(deftest current-predicate-uses-logical-update-snapshot ()
  (let ((rulebase (make-rulebase))
        (seen '()))
    (rulebase-insert-clause! rulebase (make-clause '(alpha first)))
    (rulebase-insert-clause! rulebase (make-clause '(alpha second)))
    (rulebase-insert-clause! rulebase (make-clause '(beta)))
    (map-prolog-solutions
     (lambda (solution)
       (push (solution-binding '?indicator solution) seen)
       (rulebase-insert-clause! rulebase (make-clause '(gamma added))))
     rulebase '(current-predicate ?indicator))
    (is-equal '((alpha / 1) (beta / 0)) (nreverse seen))
    (assert-query rulebase (current-predicate (gamma / 1)) :succeeds)))

(deftest-queries list-builtins ((make-rulebase))
  ((member ?x (bob alice))       :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))      => (nil))
  ((and (member ?x (a b . ?tail)) (= ?tail end))
                                   => (((?x . a) (?tail . end))
                                       ((?x . b) (?tail . end))) :limit 2)
  ((and (member wanted ?unbound) (= ?unbound (wanted tail)))
                                   => (((?unbound wanted tail))) :limit 1)
  ((append (a b) (c) ?xs)        => (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c))  => (((?tail . (c)))))
  ((append ?left ?right (a b c)) => (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append (a . ?tail) (c) (a b c))
                                   => (((?tail . (b)))))
  ((and (append ?left ?right ?any) (= ?any (a b)))
                                   => (((?left . ()) (?right . (a b)) (?any a b))
                                       ((?left . (a)) (?right . (b)) (?any a b))
                                       ((?left . (a b)) (?right . ()) (?any a b))) :limit 3)
  ((reverse (a b c) ?x)          => (((?x . (c b a)))))
  ((reverse ?x (c b a))          => (((?x . (a b c)))))
  ((reverse atom other)          :fails)
  ((length (a b c) ?n)           => (((?n . 3))))
  ((length ?xs 0)                => (((?xs))))
  ((length ?xs 2)                :succeeds)
  ((length ?xs -1)               :fails)
  ((length ?xs not-a-number)     :fails))

(deftest-queries arithmetic-builtins ((make-rulebase))
  ((is ?x (+ 2 (* 3 4)))         => (((?x . 14))))
  ((is ?x (- 5))                 => (((?x . -5))))
  ((is ?x (- 10 3))              => (((?x . 7))))
  ((is ?x (/ 7 2))               => (((?x . 7/2))))
  ((is ?x (mod 17 5))            => (((?x . 2))))
  ((is ?x (abs -9))              => (((?x . 9))))
  ((is ?x (// -7 3))             => (((?x . -2))))
  ((is ?x (div -7 3))            => (((?x . -3))))
  ((is ?x (rem -7 3))            => (((?x . -1))))
  ((is ?x (mod -7 3))            => (((?x . 2))))
  ((is ?x (sign -7))             => (((?x . -1))))
  ((is ?x (min 7 3))             => (((?x . 3))))
  ((is ?x (max 7 3))             => (((?x . 7))))
  ((is ?x (floor 7/3))           => (((?x . 2))))
  ((is ?x (ceiling 7/3))         => (((?x . 3))))
  ((is ?x (truncate -7/3))       => (((?x . -2))))
  ((is ?x (round 5/2))           => (((?x . 2))))
  ((is ?x (** 2 8))              => (((?x . 256))))
  ((is ?x (^ 3 3))               => (((?x . 27))))
  ((is ?x (+ 3))                 => (((?x . 3))))
  ((is 3 (+ 1 2))                :succeeds)
  ((is 4 (+ 1 2))                :fails)
  ((|=:=| (+ 1 2) 3)             :succeeds)
  ((|=:=| 3 4)                   :fails)
  ((|=\\=| 3 4)                  :succeeds)
  ((|=\\=| 3 (+ 1 2))            :fails)
  ((< 2 3)                       :succeeds)
  ((< 3 2)                       :fails)
  ((=< 3 3)                      :succeeds)
  ((> 4 3)                       :succeeds)
  ((>= 4 4)                      :succeeds)
  ((and (= ?x 4) (is ?y (+ ?x 1))) => (((?x . 4) (?y . 5))))
  ((is ?x (+ ?unbound 1))        :signals)
  ((is ?x (+ atom 1))            :signals)
  ((is ?x (/ 1 0))               :signals)
  ((is ?x (// 1 0))              :signals)
  ((is ?x (rem 1.0 2))           :signals)
  ((is ?x (mod 1 0))             :signals))

(deftest-queries goal-shapes ((prolog ((ready))
                                      ((stuck ?in ?out) (= ?in ?out))))
  (ready                         => (nil))
  ((ready)                       => (nil))
  (missing                       :fails)
  (()                            => (nil))
  (!                             => (nil))
  (((!) (= left left))           => (nil))
  ((or ! (= left right))         => (nil))
  (42                            :signals)
  (((1 2) (= a a))               :signals)
  ((= only-one)                  :signals)
  ((append a b)                  :signals)
  ((not x y)                     :signals)
  ((dcg-alt)                     :signals)
  ((dcg-token-match :noun stream) :signals))
