;;;; Query-oriented engine and builtin behavior tests.

(in-package #:fx.prolog.tests)

(deftest-queries family-relations ((make-family-rulebase))
  ((ancestor tom ?who)           => (((?who . bob)) ((?who . alice)) ((?who . eve))))
  ((ancestor ?x eve)             :set (((?x . tom)) ((?x . bob)) ((?x . alice))))
  ((ancestor ?x bob)             :first ((?x . tom)))
  ((grandparent tom ?z)          => (((?z . alice))))
  ((ancestor tom eve)            :succeeds)
  ((ancestor eve tom)            :fails)
  ((adult ?x)                    :set (((?x . tom)) ((?x . bob)) ((?x . alice)))))

(deftest-queries control-flow-builtins ((make-family-rulebase))
  ((= ?x left)                   => (((?x . left))))
  ((= left right)                :fails)
  ((/= tom alice)                => (nil))
  ((/= ?x ?y)                    :fails)
  ((/= tom alice)                :succeeds)
  ((not (parent alice tom))      => (nil))
  ((not (parent tom bob))        :fails)
  ((and)                         => (nil))
  ((and (parent tom bob) (parent bob alice)) => (nil))
  ((and (parent tom ?x) (parent ?x alice))   => (((?x . bob))))
  ((or (= ?x left) (= ?x right)) :set (((?x . left)) ((?x . right))))
  ((or)                          :fails)
  ((or (parent eve ?x))          :fails))

(deftest-queries list-builtins ((make-rulebase))
  ((member ?x (bob alice))       :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))      => (nil))
  ((member ?x (a . b))           :fails)
  ((member ?x ?unbound)          :fails)
  ((append (a b) (c) ?xs)        => (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c))  => (((?tail . (c)))))
  ((append ?left ?right (a b c)) => (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append ?left ?right ?any)    :fails)
  ((reverse (a b c) ?x)          => (((?x . (c b a)))))
  ((reverse ?x (c b a))          => (((?x . (a b c)))))
  ((reverse atom other)          :fails)
  ((length (a b c) ?n)           => (((?n . 3))))
  ((length ?xs 0)                => (((?xs))))
  ((length ?xs 2)                :succeeds)
  ((length ?xs -1)               :fails)
  ((length ?xs not-a-number)     :fails))

(deftest-queries goal-shapes ((prolog ((ready))
                                      ((stuck ?in ?out) (= ?in ?out))))
  (ready                         => (nil))
  ((ready)                       => (nil))
  (missing                       :fails)
  (()                            => (nil))
  (!                             => (nil))
  (((!) (= left left))           => (nil))
  ((or ! (= left right))         => (nil))
  (42                            :signals)
  (((1 2) (= a a))               :signals)
  ((= only-one)                  :signals)
  ((append a b)                  :signals)
  ((not x y)                     :signals)
  ((dcg-alt)                     :signals)
  ((dcg-token-match :noun stream) :signals))
