;;;; Query-oriented engine and builtin behavior tests.

(in-package #:cl-prolog.tests)

(deftest-queries family-relations ((make-family-rulebase))
  ((ancestor tom ?who)           => (((?who . bob)) ((?who . alice)) ((?who . eve))))
  ((ancestor ?x eve)             :set (((?x . tom)) ((?x . bob)) ((?x . alice))))
  ((ancestor ?x bob)             :first ((?x . tom)))
  ((grandparent tom ?z)          => (((?z . alice))))
  ((ancestor tom eve)            :succeeds)
  ((ancestor eve tom)            :fails)
  ((adult ?x)                    :set (((?x . tom)) ((?x . bob)) ((?x . alice)))))

(deftest-queries control-flow-builtins ((make-family-rulebase))
  ((true)                        => (nil))
  ((= ?x left)                   => (((?x . left))))
  ((= left right)                :fails)
  ((/= tom alice)                => (nil))
  ((/= ?x ?y)                    :fails)
  ((/= tom alice)                :succeeds)
  ((!= tom alice)                => (nil))
  ((!= ?x ?y)                    :fails)
  ((!= tom alice)                :succeeds)
  ((not (parent alice tom))      => (nil))
  ((not (parent tom bob))        :fails)
  ((and)                         => (nil))
  ((and (parent tom bob) (parent bob alice)) => (nil))
  ((and (parent tom ?x) (parent ?x alice))   => (((?x . bob))))
  ((or (= ?x left) (= ?x right)) :set (((?x . left)) ((?x . right))))
  ((or)                          :fails)
  ((or (parent eve ?x))          :fails)
  ((call (choice ?x))            => (((?x . left)) ((?x . right))))
  ((and (= ?goal (choice ?x)) (call ?goal))
                                   => (((?goal choice left) (?x . left))
                                       ((?goal choice right) (?x . right))))
  ((once (choice ?x))            => (((?x . left))))
  ((once (parent nobody ?x))     :fails)
  ((repeat)                      => (nil nil nil) :limit 3))

(deftest-queries solution-collection-builtins
    ((make-rulebase
      :clauses (list (make-clause '(edge a 2))
                     (make-clause '(edge a 1))
                     (make-clause '(edge a 2))
                     (make-clause '(edge b 3)))))
  ((findall ?value (edge a ?value) ?bag)
                                   => (((?value . ?value) (?bag 2 1 2))))
  ((findall ?value (edge missing ?value) ?bag)
                                   => (((?value . ?value) (?bag))))
  ((bagof ?value (edge ?key ?value) ?bag)
                                   => (((?value . ?value) (?key . a) (?bag 2 1 2))
                                       ((?value . ?value) (?key . b) (?bag 3))))
  ((bagof ?value (^ ?key (edge ?key ?value)) ?bag)
                                   => (((?value . ?value) (?key . ?key)
                                        (?bag 2 1 2 3))))
  ((bagof ?value (edge missing ?value) ?bag) :fails)
  ((setof ?value (edge ?key ?value) ?bag)
                                   => (((?value . ?value) (?key . a) (?bag 1 2))
                                       ((?value . ?value) (?key . b) (?bag 3))))
  ((setof ?value (edge missing ?value) ?bag) :fails))

(deftest dynamic-database-builtins ()
  (let ((rulebase (make-rulebase)))
    (rulebase-insert-clause! rulebase (make-clause '(ordered first)))
    (rulebase-insert-clause! rulebase (make-clause '(ordered second)))
    (assert-query rulebase (ordered ?value)
                  => (((?value . first)) ((?value . second))))
    (assert-query rulebase (assertz (color apple red)) :succeeds)
    (assert-query rulebase (assertz (color apple blue)) :succeeds)
    (assert-query rulebase (asserta (color apple green)) :succeeds)
    (assert-query rulebase (color apple ?shade)
                  => (((?shade . green)) ((?shade . red)) ((?shade . blue))))
    (assert-query rulebase
                  (assertz (:- (warm ?x) (color ?x red))) :succeeds)
    (assert-query rulebase (warm apple) :succeeds)
    (assert-query rulebase (clause (color apple red) ?body)
                  => (((?body . true))))
    (assert-query rulebase (clause (warm apple) (color apple red)) :succeeds)
    (assert-query rulebase (retract (color apple ?shade))
                  :first ((?shade . green)))
    (assert-query rulebase (color apple ?shade)
                  => (((?shade . red)) ((?shade . blue))))
    (assert-query rulebase (abolish (color / 2)) :succeeds)
    (assert-query rulebase (color apple ?shade) :fails)
    (assert-query rulebase (assertz (= left left)) :signals)
    (assert-query rulebase (clause (= left left) ?body) :signals)
    (assert-query rulebase (abolish (= / 2)) :signals)))

(deftest-queries list-builtins ((make-rulebase))
  ((member ?x (bob alice))       :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))      => (nil))
  ((member ?x (a . b))           :fails)
  ((member ?x ?unbound)          :fails)
  ((append (a b) (c) ?xs)        => (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c))  => (((?tail . (c)))))
  ((append ?left ?right (a b c)) => (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append ?left ?right ?any)    :fails)
  ((reverse (a b c) ?x)          => (((?x . (c b a)))))
  ((reverse ?x (c b a))          => (((?x . (a b c)))))
  ((reverse atom other)          :fails)
  ((length (a b c) ?n)           => (((?n . 3))))
  ((length ?xs 0)                => (((?xs))))
  ((length ?xs 2)                :succeeds)
  ((length ?xs -1)               :fails)
  ((length ?xs not-a-number)     :fails))

(deftest-queries arithmetic-builtins ((make-rulebase))
  ((is ?x (+ 2 (* 3 4)))         => (((?x . 14))))
  ((is ?x (- 5))                 => (((?x . -5))))
  ((is ?x (- 10 3))              => (((?x . 7))))
  ((is ?x (/ 7 2))               => (((?x . 7/2))))
  ((is ?x (mod 17 5))            => (((?x . 2))))
  ((is ?x (abs -9))              => (((?x . 9))))
  ((is 3 (+ 1 2))                :succeeds)
  ((is 4 (+ 1 2))                :fails)
  ((|=:=| (+ 1 2) 3)             :succeeds)
  ((|=:=| 3 4)                   :fails)
  ((|=\\=| 3 4)                  :succeeds)
  ((|=\\=| 3 (+ 1 2))            :fails)
  ((< 2 3)                       :succeeds)
  ((< 3 2)                       :fails)
  ((=< 3 3)                      :succeeds)
  ((> 4 3)                       :succeeds)
  ((>= 4 4)                      :succeeds)
  ((and (= ?x 4) (is ?y (+ ?x 1))) => (((?x . 4) (?y . 5))))
  ((is ?x (+ ?unbound 1))        :signals)
  ((is ?x (+ atom 1))            :signals)
  ((is ?x (/ 1 0))               :signals)
  ((is ?x (mod 1 0))             :signals))

(deftest-queries goal-shapes ((prolog ((ready))
                                      ((stuck ?in ?out) (= ?in ?out))))
  (ready                         => (nil))
  ((ready)                       => (nil))
  (missing                       :fails)
  (()                            => (nil))
  (!                             => (nil))
  (((!) (= left left))           => (nil))
  ((or ! (= left right))         => (nil))
  (42                            :signals)
  (((1 2) (= a a))               :signals)
  ((= only-one)                  :signals)
  ((append a b)                  :signals)
  ((not x y)                     :signals)
  ((dcg-alt)                     :signals)
  ((dcg-token-match :noun stream) :signals))
