;;;; Engine surface, data model, and macro behavior tests.

(in-package #:fx.prolog.tests)

(deftest-table package-surface ()
  (:is (find-package "FX.PROLOG"))
  (:exported "PROLOG" "FX.PROLOG")
  (:exported "QUERY-PROLOG" "FX.PROLOG")
  (:exported "MAP-PROLOG-SOLUTIONS" "FX.PROLOG")
  (:not-exported "DEFINE-BUILTIN" "FX.PROLOG")
  (:exported "DEF-RULE" "FX.PROLOG")
  (:exported "PHRASE" "FX.PROLOG")
  (:exported "UNIFY" "FX.PROLOG")
  (:exported "LOGIC-SUBSTITUTE" "FX.PROLOG")
  (:exported "FRESH-LOGIC-VARIABLE" "FX.PROLOG")
  (:exported "INVALID-GOAL-ERROR" "FX.PROLOG")
  (:not-exported "SUBSTITUTE-TERM" "FX.PROLOG")
  (:not-exported "*MAX-PROOF-DEPTH*" "FX.PROLOG")
  (:not-exported "UNIFY-FAILED-P" "FX.PROLOG")
  (:not-exported "WHEN-UNIFY-SUCCEEDS" "FX.PROLOG")
  (:not-exported "WHEN-UNIFY-FAILS" "FX.PROLOG")
  (:not-exported "QUERY-PROLOG-CPS" "FX.PROLOG")
  (:not-exported "PROLOG-SUCCEEDS-P-CPS" "FX.PROLOG")
  (:is (logic-var-p '?x))
  (:is (logic-var-p (fresh-logic-variable)))
  (:is-not (logic-var-p :?keyword))
  (:is-not (logic-var-p 'plain))
  (:is-not (logic-var-p (make-symbol "")))
  (:is-not (logic-var-p 42)))

(deftest rulebase-data-model ()
  (let ((rb (prolog
              ((parent tom bob))
              ((parent bob alice))
              ((ancestor ?x ?y) (parent ?x ?y))
              ((ancestor ?x ?y) (parent ?x ?z) (ancestor ?z ?y)))))
    (is (rulebase-p rb))
    (is-equal 4 (length (rulebase-clauses rb)))
    (let ((fact (first (rulebase-clauses rb)))
          (rule (third (rulebase-clauses rb))))
      (is-equal '(parent tom bob) (clause-head fact))
      (is-equal '() (clause-body fact))
      (is-equal '(ancestor ?x ?y) (clause-head rule))
      (is-equal '((parent ?x ?y)) (clause-body rule)))))

(deftest-table rulebase-default-constructors ()
  (:equal '() (clause-body (make-clause '(lonely))))
  (:equal '() (rulebase-clauses (make-rulebase))))

(deftest-table prolog-invalid-clauses-signal ()
  (:signals (macroexpand-1 '(prolog (:facts (parent tom bob))))
            "Invalid PROLOG clause should fail at expansion time")
  (:signals (macroexpand-1 '(prolog (42)))
            "A clause head must be a list")
  (:signals (macroexpand-1 '(prolog ready))
            "A clause must be a list"))

(deftest-tree-contains def-rule-expands-to-clause-construction
    ((macroexpand-1 '(def-rule (warm ?x) (planet ?x))))
  make-clause
  '(warm ?x)
  '(list '(planet ?x)))

(deftest explicit-rulebase-composition ()
  (let* ((warm-rule (def-rule (warm ?x) (planet ?x)))
         (rulebase (make-rulebase
                    :clauses (list (make-clause '(planet earth))
                                   (make-clause '(inhabited ?x) '((planet ?x)))
                                   warm-rule))))
    (is-equal '(warm ?x) (clause-head warm-rule))
    (is-equal '(nil) (query-prolog rulebase '(planet earth)))
    (is-equal '(nil) (query-prolog rulebase '(inhabited earth)))
    (is-equal '(nil) (query-prolog rulebase '(warm earth)))))

(deftest extend-rulebase-shadowing ()
  (let* ((base (prolog ((color apple red))))
         (extended (extend-rulebase base
                     ((color apple green)))))
    (is-equal '(((?shade . red)))
              (query-prolog base '(color apple ?shade)))
    (is-equal '((?shade . green))
              (query-prolog-first extended '(color apple ?shade)))
    (is-equal '(((?shade . green)) ((?shade . red)))
              (query-prolog extended '(color apple ?shade)))))

(deftest assert-query-first-keeps-options ()
  (with-macroexpansion (expansion
                        '(assert-query rb (ancestor tom ?who)
                                       :first ((?who . bob))
                                       :max-depth 3
                                       :project nil))
    (is (%tree-contains-p expansion 'query-prolog-first))
    (is (%tree-contains-p expansion ':max-depth))
    (is (%tree-contains-p expansion ':project)))
  (with-macroexpansion (expansion
                        '(deftest-queries example ((make-rulebase))
                           ((ancestor tom ?who) :first ((?who . bob)) :max-depth 3)))
    (is (%tree-contains-p expansion 'query-prolog-first))
    (is (%tree-contains-p expansion ':max-depth))))

(deftest when-guards-compile-to-closures ()
  (let ((rb (prolog
              ((score alice 42))
              ((score bob 7))
              ((high-score ?who ?n) (score ?who ?n) (:when (> ?n 10)))
              ((constant-yes) (:when t))
              ((constant-no) (:when nil)))))
    (let* ((rule (find '(high-score ?who ?n) (rulebase-clauses rb)
                       :key #'clause-head :test #'equal))
           (guard (second (clause-body rule))))
      (is (functionp (second guard)) "The :when guard must be compiled to a closure")
      (is-equal '(?n) (cddr guard)))
    (is-equal '(((?who . alice) (?n . 42)))
              (query-prolog rb '(high-score ?who ?n)))
    (is (prolog-succeeds-p rb '(constant-yes)))
    (is (not (prolog-succeeds-p rb '(constant-no))))))

(deftest when-guard-shape-is-strict ()
  (is (fx.prolog::%when-guard-p '(:when (> ?n 1))))
  (is (not (fx.prolog::%when-guard-p '(:when))))
  (is (not (fx.prolog::%when-guard-p '(:when f ?x))))
  (is (not (fx.prolog::%when-guard-p 'ready)))
  (let ((rb (prolog
              ((ready))
              ((launchable) ready))))
    (is-equal '(nil) (query-prolog rb '(launchable)))))

(deftest guards-nest-inside-control-goals ()
  (let ((rb (prolog
              ((n 1)) ((n 2)) ((n 3))
              ((odd-n ?x) (n ?x) (not (:when (evenp ?x))))
              ((tagged ?x ?tag)
               (n ?x)
               (or ((:when (= ?x 1)) (= ?tag one))
                   (= ?tag other))))))
    (is-equal '(((?x . 1)) ((?x . 3))) (query-prolog rb '(odd-n ?x)))
    (is-same-set '(((?tag . one)) ((?tag . other)))
                 (query-prolog rb '(tagged 1 ?tag)))
    (is-equal '(((?tag . other)))
              (query-prolog rb '(tagged 2 ?tag)))))

(deftest def-rule-compiles-when-guards ()
  (with-macroexpansion (expansion
                        '(def-rule (even ?x)
                           (n ?x)
                           (:when (evenp ?x))))
    (is (%tree-contains-p expansion 'make-clause))
    (is (%tree-contains-p expansion 'lambda))
    (is (%tree-contains-p expansion 'evenp))
    (is (not (%tree-contains-p expansion 'eval-when)))
    (is (not (%tree-contains-p expansion 'eval)))))

(deftest with-prolog-query-and-match ()
  (let ((rb (make-family-rulebase))
        (seen nil))
    (with-prolog-query (?x) (rb '(ancestor ?x bob))
      (setf seen ?x))
    (is-equal 'tom seen)
    (with-prolog-query (?x) (rb '(ancestor eve tom))
      (setf seen :should-not-run))
    (is-equal 'tom seen)
    (is-equal :direct
              (prolog-match rb
                ((parent tom bob) :direct)
                ((ancestor eve tom) :wrong)
                ((ancestor tom eve) :fallback)))
    (is-equal nil
              (prolog-match rb
                ((parent eve tom) :never)))))
