;;;; Engine, builtin, and query-API behavior tests.

(in-package #:fx.prolog.tests)

(deftest-queries family-relations ((make-family-rulebase))
  ((ancestor tom ?who)          => (((?who . bob)) ((?who . alice)) ((?who . eve))))
  ((ancestor ?x eve)            :set (((?x . tom)) ((?x . bob)) ((?x . alice))))
  ((ancestor ?x bob)            :first ((?x . tom)))
  ((grandparent tom ?z)         => (((?z . alice))))
  ((ancestor tom eve)           :succeeds)
  ((ancestor eve tom)           :fails)
  ((adult ?x)                   :set (((?x . tom)) ((?x . bob)) ((?x . alice)))))

(deftest-queries control-flow-builtins ((make-family-rulebase))
  ((= ?x left)                  => (((?x . left))))
  ((= left right)               :fails)
  ((!= tom alice)               => (nil))
  ((!= ?x ?y)                   :fails)
  ((/= tom alice)               :succeeds)
  ((not (parent alice tom))     => (nil))
  ((not (parent tom bob))       :fails)
  ((and)                        => (nil))
  ((and (parent tom bob) (parent bob alice)) => (nil))
  ((and (parent tom ?x) (parent ?x alice))   => (((?x . bob))))
  ((or (= ?x left) (= ?x right)) :set (((?x . left)) ((?x . right))))
  ((or)                         :fails)
  ((or (parent eve ?x))         :fails))

(deftest-queries list-builtins ((make-empty-rulebase))
  ((member ?x (bob alice))      :set (((?x . bob)) ((?x . alice))))
  ((member bob (bob alice))     => (nil))
  ((member ?x (a . b))          :fails)
  ((member ?x ?unbound)         :fails)
  ((append (a b) (c) ?xs)       => (((?xs . (a b c)))))
  ((append (a b) ?tail (a b c)) => (((?tail . (c)))))
  ((append ?left ?right (a b c)) => (((?left . ()) (?right . (a b c)))
                                     ((?left . (a)) (?right . (b c)))
                                     ((?left . (a b)) (?right . (c)))
                                     ((?left . (a b c)) (?right . ()))))
  ((append ?left ?right ?any)   :fails)
  ((reverse (a b c) ?x)         => (((?x . (c b a)))))
  ((reverse ?x (c b a))         => (((?x . (a b c)))))
  ((reverse atom other)         :fails)
  ((length (a b c) ?n)          => (((?n . 3))))
  ((length ?xs 0)               => (((?xs))))
  ((length ?xs 2)               :succeeds)
  ((length ?xs -1)              :fails)
  ((length ?xs not-a-number)    :fails))

(deftest-queries goal-shapes ((prolog ((ready))
                                      ((stuck ?in ?out) (= ?in ?out))))
  (ready                        => (nil))
  ((ready)                      => (nil))
  (missing                      :fails)
  (()                           => (nil))
  (!                            => (nil))
  (((!) (= left left))          => (nil))
  ((or ! (= left right))        => (nil))
  (42                           :signals)
  (((1 2) (= a a))              :signals)
  ((= only-one)                 :signals)
  ((append a b)                 :signals)
  ((not x y)                    :signals)
  ((dcg-alt)                    :signals)
  ((dcg-token-match :noun stream) :signals))

(deftest cut-prunes-clause-alternatives ()
  (let ((rb (prolog
              ((choice left))
              ((choice right))
              ((pick ?x) (choice ?x) !)
              ((pick fallback) (choice left)))))
    ;; the cut commits to the first CHOICE solution and prunes the
    ;; remaining PICK clauses
    (is-equal '(((?x . left))) (query-prolog rb '(pick ?x)))
    ;; a cut at query level prunes earlier goals' choice points
    (is-equal '(((?x . left))) (query-prolog rb '((choice ?x) !)))
    ;; a cut inside AND propagates through the wrapping goal
    (is-equal '(((?x . left))) (query-prolog rb '(and (choice ?x) !)))))

(deftest degenerate-rules-are-ignored ()
  (let ((rb (make-empty-rulebase)))
    (assert-rule! rb (make-rule :body '((anything))))
    (assert-fact! rb (make-fact :predicate 'ready))
    (is-equal '(nil) (query-prolog rb '(ready)))))

(deftest facts-are-tried-before-rules ()
  (let ((rb (prolog
              ((color red))
              ((color ?x) (= ?x derived)))))
    (is-equal '(((?x . red)) ((?x . derived)))
              (query-prolog rb '(color ?x)))))

(deftest depth-bound-terminates-recursion ()
  (let ((rb (prolog
              ((loop-forever) (loop-forever)))))
    (is-equal '() (query-prolog rb '(loop-forever) :max-depth 16))
    (is (not (prolog-succeeds-p rb '(loop-forever))))))

(deftest foreign-predicate-hook ()
  (let ((rb (make-family-rulebase))
        (*recorded-colors* '()))
    (is-equal '(nil) (query-prolog rb '(accepted :ok)))
    (is-equal '() (query-prolog rb '(accepted :ng)))
    (is-equal '(((?x . tom))) (query-prolog rb '(colored ?x)))
    (is-equal '(tom) *recorded-colors*)))

(deftest runtime-when-guards-take-functions ()
  (let ((rb (make-family-rulebase)))
    (is-equal '(((?x . bob)))
              (query-prolog rb (list 'and
                                     '(parent tom ?x)
                                     (list :when (lambda (x) (eq x 'bob)) '?x))))
    ;; expression-style guards are no longer evaluated
    (is (signals-error (query-prolog rb '(:when (equal 'bob 'bob)))))))

(deftest query-limits-and-streaming ()
  (let ((rb (make-family-rulebase)))
    (is-equal '(((?who . bob))) (query-prolog rb '(ancestor tom ?who) :limit 1))
    (is-equal 2 (length (query-prolog rb '(ancestor tom ?who) :limit 2)))
    (is (signals-error (query-prolog rb '(ancestor tom ?who) :limit 0)))
    (let ((seen '()))
      (map-prolog-solutions (lambda (solution) (push solution seen))
                            rb '(ancestor tom ?who) :limit 2)
      (is-equal '(((?who . bob)) ((?who . alice))) (reverse seen)))
    (let ((raw (query-prolog rb '(ancestor ?x bob) :project nil)))
      (is-equal 1 (length raw))
      (is (assoc '?x (first raw))))
    (is-equal '() (query-prolog rb '(ancestor tom ?who) :max-depth -1))))

(deftest rule-variables-are-freshened-per-use ()
  (let ((rb (prolog
              ((same ?x ?x))
              ((both ?a ?b) (same ?a ?a) (same ?b ?b)))))
    (is-equal '(((?p . 1) (?q . 2)))
              (query-prolog rb '((same ?p 1) (same ?q 2) (both ?p ?q))))))

(deftest define-builtin-is-extensible ()
  (let ((name (gensym "TWICE")))
    (eval `(define-builtin (,name input output) (rulebase environment depth emit)
             (let ((value (logic-substitute input environment)))
               (when (numberp value)
                 (fx.prolog::%unify-emit output (* 2 value) environment emit)))))
    (is-equal '(((?y . 6)))
              (query-prolog (make-empty-rulebase) (list name 3 '?y)))))

(deftest invalid-goal-error-reports-context ()
  (handler-case
      (progn
        (query-prolog (make-empty-rulebase) '(= a))
        (error "Expected an INVALID-GOAL-ERROR"))
    (invalid-goal-error (condition)
      (is-equal '(= a) (invalid-goal-error-goal condition))
      (is (search "expects" (princ-to-string condition))))))

(deftest query-normalization-internals ()
  (is-equal '() (fx.prolog::%normalize-query nil))
  (is-equal '((parent tom bob))
            (fx.prolog::%normalize-query '(parent tom bob)))
  (is-equal '((parent tom bob) (parent bob alice))
            (fx.prolog::%normalize-query '((parent tom bob) (parent bob alice))))
  (is-equal '(!) (fx.prolog::%normalize-query '!))
  (is-equal '(unless (minusp depth) (run))
            (macroexpand-1 '(fx.prolog::%with-depth-guard depth (run)))))
