(in-package #:cl-prolog.tests)

(deftest prolog-flag-values-follow-rulebase-transactions ()
  (let* ((rulebase (make-rulebase))
         (transaction (cl-prolog::%copy-rulebase rulebase)))
    (assert-query transaction (cl-prolog::set_prolog_flag unknown cl-prolog:fail) :succeeds)
    (assert-query rulebase
                  (cl-prolog::current_prolog_flag unknown cl-prolog.user-atoms::error)
                  :succeeds)
    (cl-prolog::%replace-rulebase! rulebase transaction)
    (assert-query rulebase (cl-prolog::current_prolog_flag unknown cl-prolog:fail) :succeeds)))

(deftest prolog-flag-values-are-rulebase-local ()
  (let ((changed (make-rulebase))
        (unchanged (make-rulebase)))
    (assert-query changed (cl-prolog::set_prolog_flag debug cl-prolog::on) :succeeds)
    (assert-query changed (cl-prolog::current_prolog_flag debug cl-prolog::on) :succeeds)
    (assert-query unchanged (cl-prolog::current_prolog_flag debug cl-prolog::off) :succeeds)))

(deftest prolog-flag-mutation-is-observable-within-one-rulebase ()
  (let ((rulebase (make-rulebase)))
    (assert-query rulebase (cl-prolog::set_prolog_flag debug cl-prolog::on) :succeeds)
    (assert-query rulebase (cl-prolog::current_prolog_flag debug cl-prolog::on) :succeeds)))

(deftest-queries prolog-flag-builtins ((make-rulebase))
  ((cl-prolog::current_prolog_flag bounded ?value) => (((?value . cl-prolog:false))))
  ((cl-prolog::current_prolog_flag max_arity ?value) => (((?value . cl-prolog::unbounded))))
  ((cl-prolog::current_prolog_flag unknown ?value) => (((?value . cl-prolog.user-atoms::error))))
  ((cl-prolog::current_prolog_flag missing ?value) :fails)
  ((cl-prolog::current_prolog_flag ?name ?value) :set
   (((?name . cl-prolog::bounded) (?value . cl-prolog:false))
    ((?name . cl-prolog::max_arity) (?value . cl-prolog::unbounded))
    ((?name . cl-prolog::integer_rounding_function) (?value . cl-prolog::toward_zero))
    ((?name . cl-prolog::char_conversion) (?value . cl-prolog::off))
    ((?name . cl-prolog.user-atoms::debug) (?value . cl-prolog::off))
    ((?name . cl-prolog::unknown) (?value . cl-prolog.user-atoms::error))
    ((?name . cl-prolog::double_quotes) (?value . cl-prolog::codes))))
  ((cl-prolog::set_prolog_flag debug cl-prolog::on) :succeeds)
  ((cl-prolog::set_prolog_flag debug cl-prolog::off) :succeeds)
  ((cl-prolog::current_prolog_flag debug cl-prolog::off) :succeeds)
  ((cl-prolog::set_prolog_flag ?name on) :signals)
  ((cl-prolog::set_prolog_flag debug ?value) :signals)
  ((cl-prolog::set_prolog_flag missing on) :signals)
  ((cl-prolog::set_prolog_flag debug invalid) :signals)
  ((cl-prolog::set_prolog_flag bounded false) :signals)
  ((cl-prolog::current_prolog_flag 7 ?value) :signals))
