;;;; Conventional Prolog source parser tests.

(in-package #:cl-prolog.tests)

(deftest prolog-term-parser ()
  (is-equal '(cl-prolog::person cl-prolog::|Mary Jane| 12 1.5d0)
            (read-prolog-term "person('Mary Jane', 12, 1.5)."))
  (is-equal '(cl-prolog::a cl-prolog::b cl-prolog::c)
            (read-prolog-term "[a,b,c]"))
  (is-equal '(cl-prolog::a cl-prolog::b . cl-prolog::?TAIL)
             (read-prolog-term "[a,b|Tail]"))
  (is-equal 1000.0d0 (read-prolog-term "1e3"))
  (is-equal 0.015d0 (read-prolog-term "1.5e-2"))
  (signals-error (read-prolog-term "[a|X,Y]"))
  (let ((term (read-prolog-term "pair(X, X, _, _)")))
    (is (eq (second term) (third term)))
    (is (not (eq (fourth term) (fifth term)))))
  (let ((nil-atom (read-prolog-term "nil"))
        (car-atom (read-prolog-term "car")))
    (is (not (null nil-atom)))
    (is (eq nil-atom (read-prolog-term "'NIL'")))
    (is (eq (symbol-package nil-atom)
            (find-package '#:cl-prolog.user-atoms)))
    (is (not (eq car-atom 'cl:car)))
    (is-equal '() (read-prolog-term "[]"))))

(deftest prolog-stream-term-reader-is-incremental ()
  (with-input-from-string
      (stream (format nil
                      "first(1.5, 'not.a.term'). % between terms~%second([a,b])."))
    (is-equal '(cl-prolog.user-atoms::first 1.5d0 cl-prolog::|not.a.term|)
              (read-prolog-term stream))
    (is-equal '(cl-prolog.user-atoms::second (cl-prolog::a cl-prolog::b))
              (read-prolog-term stream)))
  (with-input-from-string (stream "value % comment at end of file")
    (is-equal 'cl-prolog::value (read-prolog-term stream))))

(deftest prolog-clause-parser ()
  (let ((fact (read-prolog-clause "parent(tom, bob)."))
        (rule (read-prolog-clause "ancestor(X,Y) :- parent(X,Z), ancestor(Z,Y).")))
    (is-equal '(cl-prolog::parent cl-prolog::tom cl-prolog::bob) (clause-head fact))
    (is-equal '() (clause-body fact))
    (is-equal '(cl-prolog::ancestor cl-prolog::?X cl-prolog::?Y) (clause-head rule))
    (is-equal '((cl-prolog::parent cl-prolog::?X cl-prolog::?Z)
                (cl-prolog::ancestor cl-prolog::?Z cl-prolog::?Y))
              (clause-body rule)))
  (let ((rule (read-prolog-clause "ready :- true.")))
    (is-equal '(cl-prolog::ready) (clause-head rule))
    (is-equal '(cl-prolog::true) (clause-body rule))))

(deftest prolog-operator-parser ()
  (is-equal '(cl-prolog::or (cl-prolog::and cl-prolog::p cl-prolog::q) cl-prolog::r)
            (read-prolog-term "p, q ; r"))
  (is-equal '(cl-prolog::if-then-else cl-prolog::p cl-prolog::q cl-prolog::r)
            (read-prolog-term "p -> q ; r"))
  (is-equal '(cl-prolog::soft-if-then-else cl-prolog::p cl-prolog::q cl-prolog::r)
            (read-prolog-term "p *-> q ; r"))
  (is-equal '(not (= cl-prolog::?X 1)) (read-prolog-term "\\+ X = 1"))
  (is-equal '(is cl-prolog::?X (+ 1 (* 2 3))) (read-prolog-term "X is 1 + 2 * 3"))
  (signals-error (read-prolog-term "2 ** 3 ** 4"))
  (is-equal '(cl-prolog::^ 2 (cl-prolog::^ 3 4))
            (read-prolog-term "2 ^ 3 ^ 4"))
  (is-equal '(cl-prolog::rem (cl-prolog::div (cl-prolog::// 20 3) 2) 2)
            (read-prolog-term "20 // 3 div 2 rem 2"))
  (is-equal '(cl-prolog::mod 17 5) (read-prolog-term "17 mod 5"))
  (is-equal '(cl-prolog::@< cl-prolog::a cl-prolog::b)
            (read-prolog-term "a @< b"))
  (is-equal '(cl-prolog:|\\=| cl-prolog::?X cl-prolog::?Y)
            (read-prolog-term "X \\= Y"))
  (is-equal '(cl-prolog::=.. cl-prolog::?X
              (cl-prolog::foo cl-prolog::a cl-prolog::b))
             (read-prolog-term "X =.. [foo,a,b]"))
  (dolist (operator '("=" "\\=" "==" "\\==" "=:=" "=\\=" "=.."
                      "=<" ">=" "<" ">" "is"))
    (signals-error
     (read-prolog-term (format nil "X ~A Y ~A Z" operator operator))))
  (signals-error (read-prolog-term "X = Y < Z"))
  (signals-error (read-prolog-term "X = \\+ p"))
  (is-equal '(cl-prolog::pair (+ 1 2) (* 3 4))
            (read-prolog-term "pair(1 + 2, 3 * 4)")))

(deftest prolog-operator-table-drives-parser ()
  (dolist (case '(("1 + 2 * 3" (+ 1 (* 2 3)))
                  ("8 - 3 - 1" (- (- 8 3) 1))
                  ("2 ^ 3 ^ 4" (cl-prolog::^ 2 (cl-prolog::^ 3 4)))
                  ("\\+ X = 1" (not (= cl-prolog::?X 1)))))
    (destructuring-bind (source expected) case
      (is-equal expected (read-prolog-term source))))
  (dolist (definition
           (cl-prolog::%operator-table-current
            cl-prolog::*standard-operator-table*))
    (let ((lexeme (cl-prolog::%operator-lexeme definition)))
      (if (cl-prolog::%word-operator-lexeme-p lexeme)
          (is (member lexeme (cl-prolog::%standard-operator-lexemes t)
                      :test #'string=))
          (is (member lexeme (cl-prolog::%symbolic-token-lexemes)
                      :test #'string=))))))

(deftest operator-lexeme-generation-does-not-mutate-delimiters ()
  (dotimes (index 20)
    (declare (ignore index))
    (is-equal 8
              (length (cl-prolog::%compute-symbolic-token-lexemes
                       (cl-prolog::%make-operator-table '())))))
  (is-equal 3
            (length (parse-prolog
                     "fact(a). rule(X) :- fact(X). ?- rule(X)."))))

(deftest prolog-source-parser-and-consult ()
  (let* ((source (format nil "% family~% parent(tom,bob). /* rule */~% child(X) :- parent(tom,X).~% ?- child(X)."))
         (forms (parse-prolog source)))
    (is-equal 3 (length forms))
    (is (clause-p (first forms)))
    (is (clause-p (second forms)))
    (is-equal '(cl-prolog::child cl-prolog::?X) (third forms)))
  (let ((rulebase (consult-prolog "edge(a,b). edge(b,c).")))
    (assert-query rulebase (cl-prolog::edge cl-prolog::a ?x)
                  => (((?x . cl-prolog::b)))))
  (signals-error (consult-prolog "?- true."))
  (let ((rulebase (make-rulebase)))
    (signals-error (consult-prolog "kept. ?- kept." rulebase))
    (is-equal '() (rulebase-visible-clauses rulebase))))
