;;;; Unification protocol tests.

(in-package #:cl-prolog.tests)

(deftest-unification unification-protocol
  (:substitute (pair ?x ?y) (pair left right)
               :expected (pair left right))
  (:fails (tag a) (tag b))
  (:not-ok ?x (wrap ?x))
  (:not-ok (wrap ?x) ?x)
  (:ok "same" "same")
  (:ok 7 7)
  (:not-ok 7 8)
  (:substitute (:outer (:inner . ?side) ?side)
               (:outer (:inner . :buy) ?other)
               :expected (:outer (:inner . :buy) :buy))
  (:substitute ?x ?y
               :initial-env ((?y . done))
               :expected done))

(deftest cyclic-unification-and-substitution-terminate ()
  (let ((left (cons 'node nil))
        (right (cons 'node nil))
        (different (cons 'other nil)))
    (setf (cdr left) left
          (cdr right) right
          (cdr different) different)
    (is (nth-value 1 (unify left right)))
    (is (not (nth-value 1 (unify left different))))
    (let ((copy (logic-substitute left nil)))
      (is (not (eq copy left)))
      (is (eq copy (cdr copy))))))

(deftest cyclic-substitution-preserves-sharing-and-variables ()
  (let* ((variable (fresh-logic-variable "?CYCLE"))
         (shared (cons variable nil))
         (root (cons shared shared)))
    (setf (cdr shared) shared)
    (is (cl-prolog::%term-has-variables-p root))
    (let ((copy (logic-substitute root nil)))
      (is (eq (car copy) (cdr copy)))
      (is (eq (car copy) (cdr (car copy))))
      (is (eq variable (car (car copy)))))))

(progn
  (deftest cyclic-variable-scan-and-query-collection-terminate ()
    (let ((ground-cycle (cons 'ground nil))
          (query-cycle (cons '?x nil)))
      (setf (cdr ground-cycle) ground-cycle
            (cdr query-cycle) query-cycle)
      (is (not (cl-prolog::%term-has-variables-p ground-cycle)))
      (is-equal '(?x) (cl-prolog::%collect-query-variables query-cycle))))

  (deftest question-prefixed-atoms-do-not-unify-as-variables ()
    (let ((atom (read-prolog-term "'?x'.")))
      (is (not (logic-var-p atom)))
      (is (not (nth-value 1 (unify atom 'cl-prolog::a))))
      (is (nth-value 1 (unify atom atom)))))

  (deftest indexed-alias-chain-terminates-with-linear-lookup (:timeout 3)
    (let* ((variables
             (loop repeat 50001
                   collect (fresh-logic-variable "?CHAIN")))
           (environment
             (loop for tail on variables
                   for variable = (car tail)
                   for value = (if (cdr tail) (cadr tail) :resolved)
                   collect (cons variable value)))
           (start (car variables)))
      (is (eq :resolved (cl-prolog::%walk-term start environment)))
      (is (eq :resolved (logic-substitute start environment)))
      (multiple-value-bind (extended ok)
          (unify start :resolved environment)
        (is ok)
        (is (eq extended environment)))))

  (deftest duplicate-bindings-preserve-first-binding ()
    (let* ((variable (fresh-logic-variable "?DUPLICATE"))
           (environment
             (list (cons variable nil)
                   (cons variable :ignored))))
      (is (null (cl-prolog::%walk-term variable environment)))
      (is (null (logic-substitute variable environment)))
      (multiple-value-bind (extended ok)
          (unify variable nil environment)
        (is ok)
        (is (eq extended environment)))))

  (deftest alias-cycle-operations-terminate (:timeout 2)
    (let* ((x (fresh-logic-variable "?CYCLE-X"))
           (y (fresh-logic-variable "?CYCLE-Y"))
           (self-environment (list (cons x x)))
           (cycle-environment
             (list (cons x y)
                   (cons y x))))
      (is (eq x (cl-prolog::%walk-term x self-environment)))
      (is (eq x (cl-prolog::%walk-term x cycle-environment)))
      (is (eq x (cl-prolog::%walk-term y cycle-environment)))
      (is (eq x (logic-substitute y cycle-environment)))
      (is (cl-prolog::%occurs-p x y cycle-environment))
      (multiple-value-bind (extended ok)
          (unify x y cycle-environment)
        (is ok)
        (is (eq extended cycle-environment)))
      (multiple-value-bind (extended ok)
          (unify x :resolved cycle-environment)
        (is ok)
        (is (eq (cdr extended) cycle-environment))
        (is (eq :resolved (logic-substitute x extended)))
        (is (eq :resolved (logic-substitute y extended))))
      (is (eq x (cl-prolog::%walk-term x cycle-environment)))))

  (deftest indexed-unification-updates-environment-order ()
    (let ((left-variable (fresh-logic-variable "?LEFT"))
          (right-variable (fresh-logic-variable "?RIGHT")))
      (multiple-value-bind (environment ok)
          (unify (list left-variable left-variable)
                 (list right-variable :done))
        (is ok)
        (is (eq right-variable (caar environment)))
        (is (eq :done (cdar environment)))
        (is (eq left-variable (caadr environment)))
        (is (eq right-variable (cdadr environment)))
        (is (eq :done (logic-substitute left-variable environment)))
        (is (eq :done (logic-substitute right-variable environment))))))

  (deftest occurs-check-and-input-environment-remain-persistent ()
    (let* ((x (fresh-logic-variable "?OCCURS-X"))
           (y (fresh-logic-variable "?OCCURS-Y"))
           (z (fresh-logic-variable "?PERSISTENT"))
           (binding (cons y x))
           (environment (list binding))
           (term (list 'node y)))
      (multiple-value-bind (extended ok)
          (unify x term environment)
        (is (not ok))
        (is (null extended)))
      (is (eq binding (car environment)))
      (is (eq x (cdar environment)))
      (multiple-value-bind (extended ok)
          (unify z :resolved environment)
        (is ok)
        (is (eq environment (cdr extended)))
        (is (eq binding (car environment))))
      (is (eq binding (car environment)))
      (is (eq x (cdar environment)))))

  (deftest indexed-substitution-preserves-cyclic-cons-sharing ()
    (let* ((variable (fresh-logic-variable "?SHARED"))
           (shared (cons variable nil))
           (root (cons shared shared))
           (environment (list (cons variable :resolved))))
      (setf (cdr shared) shared)
      (let ((copy (logic-substitute root environment)))
        (is (not (eq copy root)))
        (is (eq (car copy) (cdr copy)))
        (is (eq :resolved (car (car copy))))
        (is (eq (car copy) (cdr (car copy))))))))
