(in-package #:cl-prolog)

(define-builtin (asserta clause) (rulebase environment depth emit)
  (let* ((goal (list 'asserta clause))
         (entry (%clause-term-entry (logic-substitute clause environment) goal)))
    (rulebase-insert-clause! rulebase entry :position :first)
    (funcall emit environment)))

(define-builtin (assertz clause) (rulebase environment depth emit)
  (let* ((goal (list 'assertz clause))
         (entry (%clause-term-entry (logic-substitute clause environment) goal)))
    (rulebase-insert-clause! rulebase entry :position :last)
    (funcall emit environment)))

(define-builtin (retract clause) (rulebase environment depth emit)
  (let* ((goal (list 'retract clause))
         (pattern (logic-substitute clause environment)))
    (when (and (consp pattern)
               (not (eq (first pattern) ':-)))
      (%ensure-dynamic-predicate (first pattern) goal))
    (when (and (consp pattern) (eq (first pattern) ':-)
               (consp (rest pattern)) (consp (second pattern)))
      (%ensure-dynamic-predicate (first (second pattern)) goal))
    (multiple-value-bind (snapshot entries) (%rulebase-snapshot rulebase)
      (declare (cl:ignore snapshot))
      (dolist (entry entries)
        (let* ((clause-entry (%stored-clause-clause entry))
               (fresh (%freshen-dynamic-clause clause-entry))
             (stored (if (null (clause-body fresh))
                          (%entry-head fresh)
                          (list* ':- (%entry-head fresh)
                                 (clause-body fresh)))))
          (multiple-value-bind (extended ok)
              (unify clause stored environment)
            (when (and ok (%rulebase-retract-entry! rulebase entry))
              (funcall emit extended))))))))

(define-builtin (retractall clause) (rulebase environment depth emit)
  (let* ((goal (list 'retractall clause))
         (pattern (logic-substitute clause environment)))
    (cond
      ((and (consp pattern) (eq (first pattern) ':-)
            (consp (rest pattern)) (consp (second pattern)))
       (%ensure-dynamic-predicate (first (second pattern)) goal))
      ((consp pattern)
       (%ensure-dynamic-predicate (first pattern) goal)))
    (multiple-value-bind (snapshot entries) (%rulebase-snapshot rulebase)
      (declare (cl:ignore snapshot))
      (let ((matches '()))
        (dolist (entry entries)
          (let* ((fresh (%freshen-dynamic-clause (%stored-clause-clause entry)))
             (stored (if (null (clause-body fresh))
                          (%entry-head fresh)
                          (list* ':- (%entry-head fresh)
                                 (clause-body fresh)))))
            (multiple-value-bind (extended ok)
                (unify pattern stored environment)
              (declare (cl:ignore extended))
              (when ok (push entry matches)))))
        (%rulebase-retract-entries! rulebase matches)))
    (funcall emit environment)))

(define-builtin (current-predicate indicator) (rulebase environment depth emit)
  (let ((seen (make-hash-table :test #'equal))
        (indicators '()))
    (dolist (entry (rulebase-visible-clauses rulebase))
      (multiple-value-bind (predicate arity)
          (%entry-predicate-arity entry)
        (let ((candidate (list predicate '/ arity)))
          (unless (gethash candidate seen)
            (setf (gethash candidate seen) t)
            (push candidate indicators)))))
    (dolist (candidate (nreverse indicators))
      (%unify-emit indicator candidate environment emit))))

(define-builtin (abolish indicator) (rulebase environment depth emit)
  (let* ((goal (list 'abolish indicator))
         (resolved (logic-substitute indicator environment)))
    (unless (and (%proper-list-p resolved)
                 (= (length resolved) 3)
                 (symbolp (first resolved))
                 (eq (second resolved) '/)
                 (typep (third resolved) '(integer 0)))
      (%invalid-goal goal "predicate indicator must have shape (NAME / ARITY)"))
    (destructuring-bind (predicate slash arity) resolved
      (declare (cl:ignore slash))
      (%ensure-dynamic-predicate predicate goal)
      (multiple-value-bind (snapshot entries) (%rulebase-snapshot rulebase)
        (declare (cl:ignore snapshot))
        (%rulebase-retract-entries!
         rulebase
         (remove-if-not
          (lambda (stored)
            (multiple-value-bind (entry-predicate entry-arity)
                (%entry-predicate-arity (%stored-clause-clause stored))
              (and (eq predicate entry-predicate) (= arity entry-arity))))
          entries))))
    (funcall emit environment)))

(define-builtin (clause head body) (rulebase environment depth emit)
  (let ((resolved-head (logic-substitute head environment)))
    (when (consp resolved-head)
      (%ensure-dynamic-predicate (first resolved-head) (list 'clause head body)))
    (dolist (entry (rulebase-visible-clauses rulebase))
      (let ((fresh (%freshen-dynamic-clause entry)))
        (multiple-value-bind (head-environment head-ok)
            (unify head (%entry-head fresh) environment)
          (when head-ok
            (%unify-emit body (%entry-body-term fresh) head-environment emit)))))))
