;;;; Release audit JSON reporting helpers.

(in-package #:cl-prolog.release-audit)

(defun json-escaped-string (string)
  (with-output-to-string (out)
    (loop for ch across string
          do (case ch
               (#\" (write-string "\\\"" out))
               (#\\ (write-string "\\\\" out))
               (#\Backspace (write-string "\\b" out))
               (#\FormFeed (write-string "\\f" out))
               (#\Newline (write-string "\\n" out))
               (#\Return (write-string "\\r" out))
               (#\Tab (write-string "\\t" out))
               (t
                (if (< (char-code ch) 32)
                    (format out "\\u~4,'0X" (char-code ch))
                    (write-char ch out)))))))

(defun write-json-string (stream string)
  (format stream "\"~A\"" (json-escaped-string string)))

(defun write-json-result (stream result)
  (format stream "{")
  (write-json-string stream "status")
  (format stream ":")
  (write-json-string stream (string-downcase (symbol-name (getf result :status))))
  (format stream ",")
  (write-json-string stream "check")
  (format stream ":")
  (write-json-string stream (getf result :check))
  (format stream ",")
  (write-json-string stream "command")
  (format stream ":")
  (write-json-string stream (getf result :command))
  (format stream ",")
  (write-json-string stream "message")
  (format stream ":")
  (write-json-string stream (getf result :message))
  (format stream ",")
  (write-json-string stream "details")
  (format stream ":")
  (write-json-string stream (or (getf result :details) ""))
  (format stream "}"))

(defun emit-json-report ()
  (format t "{")
  (write-json-string t "report_type")
  (format t ":")
  (write-json-string t "release_audit")
  (format t ",")
  (write-json-string t "project_version")
  (format t ":")
  (write-json-string t (project-version))
  (format t ",")
  (write-json-string t "requested_checks")
  (format t ":[")
  (loop for check in *requested-checks*
        for firstp = t then nil
        do (unless firstp
             (format t ","))
           (write-json-string t check))
  (format t "],")
  (write-json-string t "dry_run")
  (format t ":~A," (if *dry-run* "true" "false"))
  (write-json-string t "ok")
  (format t ":~A," (if (zerop (final-exit-code)) "true" "false"))
  (write-json-string t "exit_code")
  (format t ":~D," (final-exit-code))
  (write-json-string t "results")
  (format t ":[")
  (loop for result in (nreverse *results*)
        for firstp = t then nil
        do (unless firstp
             (format t ","))
           (write-json-result t result))
  (format t "]}~%"))
